import type { Category } from './types';
import {
  Coffee,
  IceCream,
  Waves,
  Blend,
  Sparkles,
  CakeSlice,
  Cake,
  UtensilsCrossed,
  HeartPulse,
  Martini,
} from 'lucide-react';

export const categories: Category[] = [
  {
    id: 'classicos-do-cafe',
    name: 'Clássicos do Café',
    icon: Coffee,
    recipes: [
      {
        id: 'cappuccino-tradicional',
        name: 'Cappuccino Tradicional',
        image: 'cappuccino-tradicional',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso forte',
          '120 ml de leite vaporizado',
          '2 colheres de sopa de espuma de leite',
          '1 colher de chá de cacau em pó (opcional)',
        ],
        preparation: [
          'Extraia o espresso em uma xícara.',
          'Aqueça e vaporize o leite até criar espuma.',
          'Despeje o leite sobre o café, finalizando com a espuma.',
          'Polvilhe cacau em pó por cima.',
        ],
      },
      {
        id: 'espresso-macchiato',
        name: 'Espresso Macchiato',
        image: 'espresso-macchiato',
        prepTime: '3 min',
        servings: '1 xícara pequena',
        ingredients: [
          '30 ml de café espresso',
          '1 colher de sopa de espuma de leite',
        ],
        preparation: [
          'Extraia o espresso em uma xícara pequena.',
          'Adicione uma colher de espuma de leite no centro do café.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'cafe-latte',
        name: 'Café Latte',
        image: 'cafe-latte',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '180 ml de leite vaporizado',
          'Fina camada de espuma de leite',
        ],
        preparation: [
          'Extraia o espresso em uma xícara grande.',
          'Vaporize o leite até ficar cremoso e com uma fina camada de espuma.',
          'Despeje o leite sobre o espresso, segurando a espuma para o final.',
          'Finalize com a espuma por cima.',
        ],
      },
      {
        id: 'americano',
        name: 'Americano',
        image: 'americano',
        prepTime: '2 min',
        servings: '1 xícara',
        ingredients: ['30 ml de café espresso', '150 ml de água quente'],
        preparation: [
          'Despeje a água quente em uma xícara.',
          'Extraia o espresso diretamente sobre a água quente.',
          'Isso preserva a crema do espresso.',
        ],
      },
      {
        id: 'mocha',
        name: 'Mocha',
        image: 'mocha',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '30 ml de calda de chocolate',
          '150 ml de leite vaporizado',
          'Chantilly (opcional)',
        ],
        preparation: [
          'Despeje a calda de chocolate no fundo da xícara.',
          'Extraia o espresso sobre a calda e misture bem.',
          'Adicione o leite vaporizado.',
          'Decore com chantilly e raspas de chocolate, se desejar.',
        ],
      },
      {
        id: 'ristretto',
        name: 'Ristretto',
        image: 'ristretto',
        prepTime: '2 min',
        servings: '1 xícara pequena',
        ingredients: ['20 ml de café espresso (extração curta)'],
        preparation: [
          'Prepare um espresso usando menos água (extração de 15-20 segundos).',
          'O resultado é um café mais concentrado e doce.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'espresso-panna',
        name: 'Espresso con Panna',
        image: 'espresso-panna',
        prepTime: '4 min',
        servings: '1 xícara pequena',
        ingredients: ['30 ml de café espresso', 'Chantilly a gosto'],
        preparation: [
          'Extraia o espresso em uma xícara pequena.',
          'Cubra com uma generosa porção de chantilly fresco.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'doppio',
        name: 'Doppio (Espresso Duplo)',
        image: 'doppio',
        prepTime: '3 min',
        servings: '1 xícara',
        ingredients: ['60 ml de café espresso'],
        preparation: [
          'Extraia um espresso duplo (usando o dobro de pó de café e água).',
          'Sirva em uma xícara de cappuccino para apreciar o aroma.',
        ],
      },
      {
        id: 'cafe-bombeado',
        name: 'Café Bombeado (Prensa Francesa)',
        image: 'cafe-bombeado',
        prepTime: '6 min',
        servings: '2 xícaras',
        ingredients: ['30g de café moído grosseiramente', '500 ml de água quente (não fervente)'],
        preparation: [
          'Aqueça a prensa francesa com água quente e descarte.',
          'Adicione o café moído.',
          'Despeje a água quente, mexa e coloque a tampa com o êmbolo para cima.',
          'Deixe em infusão por 4 minutos.',
          'Pressione o êmbolo lentamente até o fundo e sirva.',
        ],
      },
      {
        id: 'aeropress-classico',
        name: 'Aeropress Clássico',
        image: 'aeropress-classico',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: ['17g de café moído médio-fino', '250 ml de água quente'],
        preparation: [
          'Monte o Aeropress com o filtro de papel e escalde.',
          'Adicione o café moído.',
          'Despeje a água, mexa e insira o êmbolo.',
          'Pressione suavemente por 20-30 segundos sobre uma xícara resistente.',
        ],
      },
    ],
  },
  {
    id: 'cafes-gelados-refrescantes',
    name: 'Cafés Gelados & Refrescantes',
    icon: IceCream,
    recipes: [
      {
        id: 'iced-latte',
        name: 'Iced Latte',
        image: 'iced-latte',
        prepTime: '5 min',
        servings: '1 copo grande',
        ingredients: [
          '50 ml de café espresso',
          '150 ml de leite frio',
          'Gelo a gosto',
          'Açúcar ou adoçante a gosto (opcional)',
        ],
        preparation: [
          'Encha um copo grande com gelo.',
          'Adicione o café espresso.',
          'Complete com o leite frio.',
          'Adoce se desejar e mexa bem.',
        ],
      },
      {
        id: 'cold-brew',
        name: 'Cold Brew',
        image: 'cold-brew',
        prepTime: '12 horas',
        servings: 'Aprox. 750 ml',
        ingredients: [
          '100g de café em grãos moído grosseiramente',
          '1 litro de água fria',
        ],
        preparation: [
          'Em um recipiente grande, misture o café moído com a água.',
          'Deixe em infusão na geladeira por 12 a 24 horas.',
          'Filtre a mistura usando um filtro de papel ou pano fino.',
          'Sirva com gelo, e adicione leite ou água se preferir mais suave.',
        ],
      },
      {
        id: 'espresso-tonica',
        name: 'Espresso Tônica',
        image: 'espresso-tonica',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de café espresso',
          '150 ml de água tônica',
          'Gelo a gosto',
          '1 fatia de limão ou laranja',
        ],
        preparation: [
          'Encha um copo com gelo.',
          'Despeje a água tônica.',
          'Extraia o espresso e despeje cuidadosamente sobre a tônica.',
          'Decore com a fatia de cítrico.',
        ],
      },
      {
        id: 'frappuccino-caramelo',
        name: 'Frappuccino de Caramelo',
        image: 'frappuccino-caramelo',
        prepTime: '8 min',
        servings: '1 copo grande',
        ingredients: [
          '50 ml de café forte frio',
          '100 ml de leite',
          '2 colheres de sopa de calda de caramelo',
          '1 xícara de gelo',
          'Chantilly para decorar',
        ],
        preparation: [
          'Bata o café, o leite, 1 colher de calda de caramelo e o gelo no liquidificador até ficar homogêneo.',
          'Decore o interior do copo com a outra colher de calda.',
          'Despeje a mistura e cubra com chantilly.',
        ],
      },
      {
        id: 'iced-americano',
        name: 'Iced Americano',
        image: 'iced-americano',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: ['60 ml de café espresso', '120 ml de água fria', 'Gelo a gosto'],
        preparation: [
          'Encha um copo com gelo.',
          'Adicione a água fria.',
          'Despeje o espresso por cima.',
          'Mexa suavemente antes de beber.',
        ],
      },
      {
        id: 'affogato',
        name: 'Affogato',
        image: 'affogato',
        prepTime: '3 min',
        servings: '1 porção',
        ingredients: ['1 bola de sorvete de baunilha', '30 ml de café espresso quente'],
        preparation: [
          'Coloque a bola de sorvete em uma taça ou xícara.',
          'Despeje o espresso quente recém-extraído sobre o sorvete.',
          'Sirva imediatamente e coma com uma colher.',
        ],
      },
      {
        id: 'cold-brew-com-leite-de-coco',
        name: 'Cold Brew com Leite de Coco',
        image: 'cold-brew-com-leite-de-coco',
        prepTime: '5 min (+ infusão)',
        servings: '1 copo',
        ingredients: [
          '150 ml de cold brew',
          '50 ml de leite de coco',
          'Gelo a gosto',
          'Flocos de coco para decorar (opcional)',
        ],
        preparation: [
          'Encha um copo com gelo.',
          'Despeje o cold brew.',
          'Adicione o leite de coco e mexa.',
          'Decore com flocos de coco.',
        ],
      },
      {
        id: 'limonada-com-cafe',
        name: 'Limonada com Café',
        image: 'limonada-com-cafe',
        prepTime: '7 min',
        servings: '1 copo',
        ingredients: [
          '100 ml de limonada fresca',
          '50 ml de café coado frio',
          'Gelo a gosto',
          'Hortelã para decorar',
        ],
        preparation: [
          'Encha um copo com gelo.',
          'Adicione a limonada.',
          'Complete com o café frio, despejando lentamente.',
          'Decore com um ramo de hortelã.',
        ],
      },
      {
        id: 'shakerato',
        name: 'Shakerato',
        image: 'shakerato',
        prepTime: '4 min',
        servings: '1 taça',
        ingredients: [
          '60 ml de café espresso',
          '1 colher de chá de açúcar (ou xarope simples)',
          'Gelo',
        ],
        preparation: [
          'Encha uma coqueteleira com gelo.',
          'Adicione o espresso e o açúcar.',
          'Agite vigorosamente por cerca de 15 segundos, até criar uma espuma densa.',
          'Coe para uma taça de martini gelada.',
        ],
      },
      {
        id: 'iced-mocha-branco',
        name: 'Iced Mocha Branco',
        image: 'iced-mocha-branco',
        prepTime: '6 min',
        servings: '1 copo grande',
        ingredients: [
          '30g de chocolate branco derretido',
          '60 ml de café espresso',
          '120 ml de leite frio',
          'Gelo a gosto',
        ],
        preparation: [
          'Misture o chocolate branco derretido com o espresso quente até dissolver.',
          'Encha um copo com gelo.',
          'Despeje a mistura de café e chocolate.',
          'Complete com leite e mexa bem.',
        ],
      },
    ],
  },
  {
    id: 'cafes-cremosos-espumados',
    name: 'Cafés Cremosos & Espumados',
    icon: Waves,
    recipes: [
      {
        id: 'flat-white',
        name: 'Flat White',
        image: 'flat-white',
        prepTime: '4 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de café espresso (duplo)',
          '120 ml de leite vaporizado com microespuma',
        ],
        preparation: [
          'Extraia o espresso duplo em uma xícara.',
          'Vaporize o leite para criar uma textura aveludada e cremosa (microespuma).',
          'Despeje o leite sobre o espresso, criando uma fina camada de espuma na superfície.',
        ],
      },
      {
        id: 'cafe-au-lait',
        name: 'Café au Lait',
        image: 'cafe-au-lait',
        prepTime: '5 min',
        servings: '1 xícara grande',
        ingredients: [
          '120 ml de café forte coado',
          '120 ml de leite aquecido',
        ],
        preparation: [
          'Prepare o café coado diretamente em uma xícara grande.',
          'Aqueça o leite sem deixar ferver.',
          'Despeje o café e o leite quente simultaneamente na xícara para misturar.',
        ],
      },
      {
        id: 'latte-macchiato',
        name: 'Latte Macchiato',
        image: 'latte-macchiato',
        prepTime: '6 min',
        servings: '1 copo de vidro',
        ingredients: [
          '200 ml de leite vaporizado',
          '30 ml de café espresso',
        ],
        preparation: [
          'Vaporize o leite e despeje em um copo alto, formando camadas.',
          'Espere a espuma se separar do leite.',
          'Extraia o espresso e despeje-o lentamente no centro do leite espumado.',
          'O café deve formar uma camada entre o leite e a espuma.',
        ],
      },
      {
        id: 'cappuccino-vienense',
        name: 'Cappuccino Vienense',
        image: 'cappuccino-vienense',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de café espresso duplo',
          'Chantilly',
          'Raspas de chocolate',
        ],
        preparation: [
          'Extraia o espresso em uma xícara.',
          'Cubra com uma generosa camada de chantilly.',
          'Decore com raspas de chocolate por cima.',
        ],
      },
      {
        id: 'cortado',
        name: 'Cortado',
        image: 'cortado',
        prepTime: '3 min',
        servings: '1 copo pequeno',
        ingredients: [
          '30 ml de café espresso',
          '30 ml de leite vaporizado',
        ],
        preparation: [
          'Extraia o espresso em um copo pequeno.',
          'Vaporize o leite para que fique cremoso, mas com pouca espuma.',
          'Despeje o leite sobre o espresso para "cortar" a acidez.',
        ],
      },
      {
        id: 'dalgona-coffee',
        name: 'Dalgona Coffee',
        image: 'dalgona-coffee',
        prepTime: '10 min',
        servings: '1 copo',
        ingredients: [
          '2 colheres de sopa de café solúvel',
          '2 colheres de sopa de açúcar',
          '2 colheres de sopa de água quente',
          '200 ml de leite frio ou quente',
        ],
        preparation: [
          'Em uma tigela, misture o café, o açúcar e a água quente.',
          'Bata com um batedor de arame (fouet) ou mixer até formar um creme espesso e claro.',
          'Sirva sobre um copo de leite.',
        ],
      },
      {
        id: 'magic-coffee',
        name: 'Magic Coffee',
        image: 'magic-coffee',
        prepTime: '4 min',
        servings: '1 xícara pequena',
        ingredients: ['30 ml de ristretto duplo', '90 ml de leite vaporizado'],
        preparation: [
          'Extraia um ristretto duplo em uma xícara de cappuccino (150ml).',
          'Vaporize o leite até obter uma textura sedosa e brilhante.',
          'Despeje sobre o ristretto, ideal para latte art.',
        ],
      },
      {
        id: 'cafe-breve',
        name: 'Café Breve',
        image: 'cafe-breve',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: ['60 ml de café espresso', '120 ml de "half-and-half" vaporizado'],
        preparation: [
          'O "half-and-half" é uma mistura de partes iguais de leite e creme de leite.',
          'Extraia o espresso em uma xícara.',
          'Vaporize o "half-and-half" até ficar espumoso e despeje sobre o café.',
        ],
      },
      {
        id: 'piccolo-latte',
        name: 'Piccolo Latte',
        image: 'piccolo-latte',
        prepTime: '4 min',
        servings: '1 copo pequeno',
        ingredients: ['30 ml de ristretto', '60-90 ml de leite vaporizado'],
        preparation: [
          'Extraia um ristretto em um copo de vidro pequeno (demitasse).',
          'Vaporize o leite e despeje sobre o ristretto.',
          'É uma versão menor e mais intensa de um latte.',
        ],
      },
      {
        id: 'mel-com-cafe',
        name: 'Mel com Café e Espuma',
        image: 'mel-com-cafe',
        prepTime: '6 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '1 colher de sopa de mel',
          '150 ml de leite vaporizado',
          'Canela em pó para decorar',
        ],
        preparation: [
          'Coloque o mel no fundo da xícara.',
          'Extraia o espresso sobre o mel e misture bem.',
          'Despeje o leite vaporizado por cima.',
          'Polvilhe canela para finalizar.',
        ],
      },
    ],
  },
  {
    id: 'cremes-pastas-de-cafe',
    name: 'Cremes & Pastas de Café',
    icon: Blend,
    recipes: [
      {
        id: 'creme-de-cafe',
        name: 'Creme de Café',
        image: 'creme-de-cafe',
        prepTime: '10 min',
        servings: '4 porções',
        ingredients: [
          '1 xícara de açúcar',
          '50g de café solúvel',
          '1 xícara de água fervente',
        ],
        preparation: [
          'Em uma batedeira, coloque o açúcar e o café solúvel.',
          'Adicione a água fervente e bata em velocidade alta por cerca de 10 minutos, até formar um creme fofo e claro.',
          'Guarde em um pote fechado no freezer. Sirva com leite quente ou frio.',
        ],
      },
      {
        id: 'pasta-de-amendoim-com-cafe',
        name: 'Pasta de Amendoim com Café',
        image: 'pasta-de-amendoim-com-cafe',
        prepTime: '8 min',
        servings: 'Aprox. 200g',
        ingredients: [
          '150g de pasta de amendoim integral',
          '1 colher de sopa de café solúvel em pó',
          '1 colher de sopa de mel ou agave',
        ],
        preparation: [
          'Em uma tigela, misture bem a pasta de amendoim, o café solúvel e o mel.',
          'Continue misturando até que a pasta fique homogênea.',
          'Sirva com pães, torradas ou frutas.',
        ],
      },
      {
        id: 'ganache-de-cafe',
        name: 'Ganache de Café',
        image: 'ganache-de-cafe',
        prepTime: '10 min',
        servings: 'Aprox. 300ml',
        ingredients: [
          '200g de chocolate meio amargo picado',
          '100g de creme de leite',
          '1 colher de sopa de café solúvel',
        ],
        preparation: [
          'Aqueça o creme de leite com o café solúvel até dissolver (não ferver).',
          'Despeje o creme quente sobre o chocolate picado.',
          'Deixe descansar por 2 minutos e depois misture até ficar liso e brilhante.',
          'Use como cobertura para bolos e sobremesas.',
        ],
      },
      {
        id: 'manteiga-de-cafe',
        name: 'Manteiga Aromatizada de Café',
        image: 'manteiga-de-cafe',
        prepTime: '10 min',
        servings: 'Aprox. 100g',
        ingredients: [
          '100g de manteiga sem sal em temperatura ambiente',
          '1 colher de chá de café extra forte moído finamente',
          '1 colher de chá de açúcar de confeiteiro',
        ],
        preparation: [
          'Em uma tigela, bata a manteiga até ficar cremosa.',
          'Adicione o café e o açúcar e misture bem.',
          'Enrole em papel manteiga, formando um cilindro, e leve à geladeira.',
          'Sirva com pães, croissants ou sobre panquecas.',
        ],
      },
      {
        id: 'doce-de-leite-com-cafe',
        name: 'Doce de Leite com Café',
        image: 'doce-de-leite-com-cafe',
        prepTime: '5 min',
        servings: 'Aprox. 400g',
        ingredients: [
          '1 lata de doce de leite de boa qualidade',
          '2 colheres de chá de café solúvel em pó',
        ],
        preparation: [
          'Misture o doce de leite com o café solúvel até que esteja completamente incorporado.',
          'Ajuste a quantidade de café a gosto.',
          'Ideal para rechear bolos, tapiocas ou comer de colher.',
        ],
      },
      {
        id: 'geleia-de-cafe',
        name: 'Geleia de Café',
        image: 'geleia-de-cafe',
        prepTime: '25 min',
        servings: 'Aprox. 250ml',
        ingredients: [
          '250 ml de café forte coado',
          '200g de açúcar',
          '1 colher de sopa de suco de limão',
          '1/2 pacote de pectina em pó',
        ],
        preparation: [
          'Em uma panela, misture o café, o açúcar, o suco de limão e a pectina.',
          'Leve ao fogo médio, mexendo sempre, até a geleia engrossar (ponto de fio).',
          'Guarde em um pote de vidro esterilizado.',
        ],
      },
      {
        id: 'creme-de-confeiteiro-de-cafe',
        name: 'Creme de Confeiteiro de Café',
        image: 'creme-de-confeiteiro-de-cafe',
        prepTime: '20 min',
        servings: 'Aprox. 500ml',
        ingredients: [
          '500 ml de leite',
          '4 gemas',
          '100g de açúcar',
          '40g de amido de milho',
          '2 colheres de sopa de café solúvel',
        ],
        preparation: [
          'Aqueça o leite com o café solúvel.',
          'Em outra tigela, bata as gemas, o açúcar e o amido.',
          'Despeje o leite quente aos poucos na mistura de gemas, mexendo sempre.',
          'Volte tudo para a panela e cozinhe em fogo baixo até engrossar.',
          'Cubra com plástico filme em contato com o creme e leve para gelar.',
        ],
      },
      {
        id: 'caramelo-de-cafe',
        name: 'Calda de Caramelo de Café',
        image: 'caramelo-de-cafe',
        prepTime: '15 min',
        servings: 'Aprox. 200ml',
        ingredients: [
          '1 xícara de açúcar',
          '1/2 xícara de café forte quente',
          '1/4 xícara de creme de leite',
        ],
        preparation: [
          'Derreta o açúcar em uma panela até formar um caramelo.',
          'Com cuidado, adicione o café quente e mexa (vai borbulhar).',
          'Retire do fogo e adicione o creme de leite, mexendo até ficar homogêneo.',
          'Use em sorvetes, pudins ou cafés.',
        ],
      },
      {
        id: 'brigadeiro-de-cafe',
        name: 'Brigadeiro de Café',
        image: 'brigadeiro-de-cafe',
        prepTime: '20 min',
        servings: '20 unidades',
        ingredients: [
          '1 lata de leite condensado',
          '1 colher de sopa de manteiga',
          '1 colher de sopa de café solúvel',
          'Chocolate granulado para enrolar',
        ],
        preparation: [
          'Em uma panela, misture o leite condensado, a manteiga e o café.',
          'Cozinhe em fogo baixo, mexendo sem parar, até desgrudar do fundo da panela.',
          'Deixe esfriar, enrole e passe no granulado.',
        ],
      },
      {
        id: 'chantilly-de-cafe',
        name: 'Chantilly de Café',
        image: 'chantilly-de-cafe',
        prepTime: '8 min',
        servings: 'Aprox. 300ml',
        ingredients: [
          '250 ml de creme de leite fresco gelado',
          '2 colheres de sopa de açúcar de confeiteiro',
          '1 colher de chá de extrato de café (ou solúvel diluído)',
        ],
        preparation: [
          'Bata o creme de leite na batedeira até começar a engrossar.',
          'Adicione o açúcar e o extrato de café.',
          'Continue batendo até atingir o ponto de chantilly firme.',
          'Use para decorar sobremesas e cafés.',
        ],
      },
    ],
  },
  {
    id: 'cafes-gourmet-autorais',
    name: 'Cafés Gourmet & Autorais',
    icon: Sparkles,
    recipes: [
      {
        id: 'cafe-com-canela-e-cardamomo',
        name: 'Café com Canela e Cardamomo',
        image: 'cafe-com-canela-e-cardamomo',
        prepTime: '6 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café coado',
          '1 pitada de canela em pó',
          '1 pitada de cardamomo em pó',
          'Leite ou açúcar a gosto',
        ],
        preparation: [
          'Prepare o café coado.',
          'Adicione a canela e o cardamomo ao café quente e mexa bem.',
          'Adicione leite ou açúcar se desejar.',
        ],
      },
      {
        id: 'latte-de-lavanda',
        name: 'Latte de Lavanda',
        image: 'latte-de-lavanda',
        prepTime: '10 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '150 ml de leite',
          '1 colher de sopa de xarope de lavanda',
        ],
        preparation: [
          'Prepare o xarope de lavanda (fervendo flores de lavanda com açúcar e água) ou use um pronto.',
          'Extraia o espresso em uma xícara.',
          'Adicione o xarope de lavanda ao espresso.',
          'Vaporize o leite e despeje sobre a mistura.',
        ],
      },
      {
        id: 'cafe-com-pimenta-e-chocolate',
        name: 'Café com Pimenta e Chocolate',
        image: 'cafe-com-pimenta-e-chocolate',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café forte',
          '2 quadrados de chocolate meio amargo',
          '1 pitada de pimenta caiena em pó',
        ],
        preparation: [
          'Prepare o café bem quente.',
          'Adicione o chocolate e a pimenta.',
          'Mexa vigorosamente até o chocolate derreter por completo.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'latte-de-pistache',
        name: 'Latte de Pistache',
        image: 'latte-de-pistache',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de espresso duplo',
          '150 ml de leite',
          '2 colheres de sopa de pasta ou xarope de pistache',
        ],
        preparation: [
          'Misture a pasta de pistache com o espresso quente na xícara.',
          'Vaporize o leite até ficar cremoso.',
          'Despeje o leite sobre a mistura de café e pistache.',
          'Decore com pistaches picados.',
        ],
      },
      {
        id: 'cafe-com-agua-de-rosas',
        name: 'Café com Água de Rosas',
        image: 'cafe-com-agua-de-rosas',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '1/2 colher de chá de água de rosas',
          '120 ml de leite vaporizado',
          'Pétalas de rosa secas para decorar',
        ],
        preparation: [
          'Misture o espresso com a água de rosas.',
          'Adicione o leite vaporizado.',
          'Decore com algumas pétalas de rosa secas na superfície.',
        ],
      },
      {
        id: 'golden-latte-com-cafe',
        name: 'Golden Latte com Café',
        image: 'golden-latte-com-cafe',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '150 ml de leite (pode ser vegetal)',
          '1/2 colher de chá de cúrcuma em pó',
          '1 pitada de pimenta preta',
          '1 colher de chá de mel ou agave',
        ],
        preparation: [
          'Aqueça o leite com a cúrcuma, a pimenta e o mel, sem ferver.',
          'Extraia o espresso na xícara.',
          'Despeje o leite dourado sobre o café e misture bem.',
        ],
      },
      {
        id: 'cafe-com-laranja-e-anis',
        name: 'Café com Laranja e Anis',
        image: 'cafe-com-laranja-e-anis',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café coado',
          '1 casca de laranja (sem a parte branca)',
          '1 estrela de anis',
        ],
        preparation: [
          'Coloque a casca de laranja e o anis na xícara.',
          'Coe o café quente diretamente sobre os aromáticos.',
          'Deixe em infusão por 2 minutos antes de beber.',
        ],
      },
      {
        id: 'latte-de-matcha-e-cafe',
        name: 'Latte de Matcha e Café (Dirty Matcha)',
        image: 'latte-de-matcha-e-cafe',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '1 colher de chá de matcha em pó',
          '50 ml de água quente',
          '150 ml de leite',
          '30 ml de espresso',
        ],
        preparation: [
          'Dissolva o matcha na água quente, batendo bem.',
          'Aqueça e vaporize o leite e despeje sobre o matcha.',
          'Extraia o espresso e despeje cuidadosamente por cima, criando camadas.',
        ],
      },
      {
        id: 'cafe-com-alecrim-e-mel',
        name: 'Café com Alecrim e Mel',
        image: 'cafe-com-alecrim-e-mel',
        prepTime: '10 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café coado',
          '1 ramo pequeno de alecrim fresco',
          '1 colher de sopa de mel',
        ],
        preparation: [
          'Aqueça o mel com o ramo de alecrim em fogo baixo por 2 minutos para infusionar.',
          'Coe o mel para uma xícara.',
          'Despeje o café quente por cima e misture.',
        ],
      },
      {
        id: 'iced-latte-de-rosas',
        name: 'Iced Latte de Rosas',
        image: 'iced-latte-de-rosas',
        prepTime: '6 min',
        servings: '1 copo',
        ingredients: [
          '60 ml de espresso',
          '150 ml de leite frio',
          '1 colher de sopa de xarope de rosas',
          'Gelo',
        ],
        preparation: [
          'Encha um copo com gelo.',
          'Adicione o xarope de rosas e o leite.',
          'Despeje o espresso por cima.',
          'Mexa antes de beber.',
        ],
      },
    ],
  },
  {
    id: 'sobremesas-com-cafe',
    name: 'Sobremesas com Café',
    icon: CakeSlice,
    recipes: [
      {
        id: 'tiramisu-classico',
        name: 'Tiramisù Clássico',
        image: 'tiramisu-classico',
        prepTime: '30 min + 4h de geladeira',
        servings: '8 porções',
        ingredients: [
          '4 gemas',
          '100g de açúcar',
          '500g de queijo mascarpone',
          '200ml de café forte, frio',
          '30 biscoitos champanhe',
          'Cacau em pó para polvilhar',
        ],
        preparation: [
          'Bata as gemas com o açúcar até obter um creme claro.',
          'Adicione o mascarpone e misture delicadamente.',
          'Molhe os biscoitos no café e faça uma camada em um refratário.',
          'Cubra com uma camada do creme de mascarpone. Repita as camadas.',
          'Leve à geladeira por pelo menos 4 horas. Polvilhe cacau antes de servir.',
        ],
      },
      {
        id: 'mousse-de-cafe',
        name: 'Mousse de Café',
        image: 'mousse-de-cafe',
        prepTime: '15 min + 2h de geladeira',
        servings: '6 porções',
        ingredients: [
          '1 lata de leite condensado',
          '1 lata de creme de leite',
          '1 xícara de café forte, frio',
          '1 envelope de gelatina sem sabor',
        ],
        preparation: [
          'Dissolva a gelatina conforme as instruções da embalagem.',
          'No liquidificador, bata o leite condensado, o creme de leite, o café e a gelatina dissolvida.',
          'Despeje em taças individuais e leve à geladeira por pelo menos 2 horas.',
        ],
      },
      {
        id: 'panna-cotta-de-cafe',
        name: 'Panna Cotta de Café',
        image: 'panna-cotta-de-cafe',
        prepTime: '15 min + 4h de geladeira',
        servings: '6 porções',
        ingredients: [
          '500ml de creme de leite fresco',
          '100g de açúcar',
          '100ml de café espresso forte',
          '1 envelope de gelatina em pó sem sabor',
        ],
        preparation: [
          'Hidrate a gelatina em 5 colheres de água.',
          'Aqueça o creme de leite, o açúcar e o café até dissolver o açúcar.',
          'Adicione a gelatina hidratada e mexa até dissolver.',
          'Distribua em formas e leve à geladeira por 4 horas.',
        ],
      },
      {
        id: 'pudim-de-cafe',
        name: 'Pudim de Café',
        image: 'pudim-de-cafe',
        prepTime: '1h30',
        servings: '8 porções',
        ingredients: [
          '1 lata de leite condensado',
          'A mesma medida de leite',
          '3 ovos',
          '1/2 xícara de café forte',
          'Calda de caramelo',
        ],
        preparation: [
          'Bata todos os ingredientes no liquidificador, exceto a calda.',
          'Despeje em uma forma caramelizada.',
          'Asse em banho-maria em forno pré-aquecido a 180°C por cerca de 1 hora.',
          'Deixe esfriar para desenformar.',
        ],
      },
      {
        id: 'brownie-de-cafe',
        name: 'Brownie de Café',
        image: 'brownie-de-cafe',
        prepTime: '45 min',
        servings: '9 porções',
        ingredients: [
          '200g de chocolate meio amargo',
          '100g de manteiga',
          '1 xícara de açúcar',
          '3 ovos',
          '1 xícara de farinha de trigo',
          '2 colheres de sopa de café solúvel',
        ],
        preparation: [
          'Derreta o chocolate com a manteiga.',
          'Misture o açúcar, os ovos e o café solúvel.',
          'Incorpore a mistura de chocolate e, por fim, a farinha.',
          'Asse em forma untada a 180°C por 25-30 minutos.',
        ],
      },
      {
        id: 'creme-brulee-de-cafe',
        name: 'Crème Brûlée de Café',
        image: 'creme-brulee-de-cafe',
        prepTime: '1h',
        servings: '4 porções',
        ingredients: [
          '500ml de creme de leite fresco',
          '100g de açúcar',
          '5 gemas',
          '50ml de café espresso',
          'Açúcar para caramelizar',
        ],
        preparation: [
          'Aqueça o creme de leite com o café.',
          'Bata as gemas com o açúcar.',
          'Incorpore o creme quente à mistura de gemas.',
          'Distribua em ramequins e asse em banho-maria a 160°C por 40 min.',
          'Gele e, antes de servir, polvilhe açúcar e queime com um maçarico.',
        ],
      },
      {
        id: 'palha-italiana-de-cafe',
        name: 'Palha Italiana de Café',
        image: 'palha-italiana-de-cafe',
        prepTime: '20 min + 2h de geladeira',
        servings: '12 porções',
        ingredients: [
          '1 lata de leite condensado',
          '1 colher de sopa de café solúvel',
          '3 colheres de sopa de chocolate em pó',
          '1 pacote de biscoito maisena quebrado',
        ],
        preparation: [
          'Faça um brigadeiro com o leite condensado, café e chocolate.',
          'Misture o biscoito quebrado ao brigadeiro.',
          'Despeje em uma forma untada, nivele e leve para gelar.',
          'Corte em quadrados e passe no açúcar de confeiteiro.',
        ],
      },
      {
        id: 'semifrio-de-cafe',
        name: 'Semifrio de Café',
        image: 'semifrio-de-cafe',
        prepTime: '30 min + 6h de freezer',
        servings: '8 porções',
        ingredients: [
          '3 gemas',
          '100g de açúcar',
          '250ml de creme de leite batido em chantilly',
          '100ml de café bem forte',
        ],
        preparation: [
          'Bata as gemas com o açúcar em banho-maria até obter um creme fofo.',
          'Retire do fogo e continue batendo até esfriar.',
          'Incorpore o café e, delicadamente, o chantilly.',
          'Despeje em uma forma e leve ao freezer por no mínimo 6 horas.',
        ],
      },
      {
        id: 'cheesecake-de-cafe',
        name: 'Cheesecake de Café',
        image: 'cheesecake-de-cafe',
        prepTime: '1h + 4h de geladeira',
        servings: '10 porções',
        ingredients: [
          '200g de biscoito triturado',
          '100g de manteiga derretida',
          '500g de cream cheese',
          '1 lata de leite condensado',
          '3 ovos',
          '100ml de café forte',
        ],
        preparation: [
          'Misture o biscoito com a manteiga e forre o fundo de uma forma.',
          'Bata o cream cheese, leite condensado, ovos e café.',
          'Despeje sobre a base e asse a 160°C por 45 minutos.',
          'Leve para gelar antes de servir.',
        ],
      },
      {
        id: 'macarons-de-cafe',
        name: 'Macarons de Café',
        image: 'macarons-de-cafe',
        prepTime: '1h30',
        servings: '20 unidades',
        ingredients: [
          '100g de farinha de amêndoas',
          '100g de açúcar de confeiteiro',
          '2 claras de ovo',
          '100g de açúcar refinado',
          '1 colher de sopa de café solúvel em pó (para a massa)',
          'Recheio de ganache de café',
        ],
        preparation: [
          'Bata as claras em neve e adicione o açúcar refinado aos poucos (merengue).',
          'Peneire a farinha, o açúcar de confeiteiro e o pó de café.',
          'Incorpore os secos ao merengue delicadamente (macaronage).',
          'Faça pequenos discos em uma assadeira e deixe secar por 30 min.',
          'Asse a 150°C por 15-20 min. Recheie com ganache de café.',
        ],
      },
    ],
  },
  {
    id: 'bolos-tortas-de-cafe',
    name: 'Bolos & Tortas de Café',
    icon: Cake,
    recipes: [
      {
        id: 'bolo-de-cafe-com-nozes',
        name: 'Bolo de Café com Nozes',
        image: 'bolo-de-cafe-com-nozes',
        prepTime: '1 hora',
        servings: '12 fatias',
        ingredients: [
          '3 ovos',
          '1 xícara de açúcar',
          '1/2 xícara de óleo',
          '1 xícara de café forte',
          '2 xícaras de farinha de trigo',
          '1 colher de sopa de fermento em pó',
          '1/2 xícara de nozes picadas',
        ],
        preparation: [
          'Bata os ovos, o açúcar и o óleo.',
          'Adicione o café и a farinha, misturando bem.',
          'Incorpore o fermento и as nozes.',
          'Asse em forno pré-aquecido a 180°C por 40 minutos.',
        ],
      },
      {
        id: 'torta-holandesa-de-cafe',
        name: 'Torta Holandesa de Café',
        image: 'torta-holandesa-de-cafe',
        prepTime: '40 min + 3h de geladeira',
        servings: '10 porções',
        ingredients: [
          '1 pacote de biscoito maisena',
          '100g de manteiga derretida',
          '1 lata de leite condensado',
          '1/2 xícara de café forte',
          '1 pacote de biscoito calipso',
          'Ganache de chocolate para cobrir',
        ],
        preparation: [
          'Triture o biscoito maisena e misture com a manteiga para forrar o fundo de uma forma.',
          'Bata o leite condensado com o café e um creme de leite até engrossar.',
          'Disponha os biscoitos calipso na lateral da forma e despeje o creme.',
          'Leve à geladeira. Cubra com ganache antes de servir.',
        ],
      },
      {
        id: 'bolo-formigueiro-com-cafe',
        name: 'Bolo Formigueiro com Café',
        image: 'bolo-formigueiro-com-cafe',
        prepTime: '50 min',
        servings: '12 fatias',
        ingredients: [
          '3 ovos',
          '1 e 1/2 xícara de açúcar',
          '1 xícara de café coado',
          '100g de manteiga',
          '2 xícaras de farinha de trigo',
          '1/2 xícara de chocolate granulado',
          '1 colher de sopa de fermento',
        ],
        preparation: [
          'Bata a manteiga com o açúcar e os ovos.',
          'Adicione o café e a farinha, alternadamente.',
          'Incorpore o chocolate granulado e o fermento.',
          'Asse em forma untada a 180°C por 35-40 minutos.',
        ],
      },
      {
        id: 'rocambole-de-cafe',
        name: 'Rocambole de Café',
        image: 'rocambole-de-cafe',
        prepTime: '1h',
        servings: '10 fatias',
        ingredients: [
          'Para a massa: 4 ovos, 4 colheres de açúcar, 4 colheres de farinha, 1 colher de café solúvel',
          'Para o recheio: Doce de leite com café',
        ],
        preparation: [
          'Bata as claras em neve, adicione as gemas e o açúcar.',
          'Incorpore a farinha e o café peneirados.',
          'Asse a massa fina em forma retangular por 15 min.',
          'Desenforme sobre um pano úmido, recheie com o doce de leite e enrole.',
        ],
      },
      {
        id: 'bolo-de-chocolate-com-calda-de-cafe',
        name: 'Bolo de Chocolate com Calda de Café',
        image: 'bolo-de-chocolate-com-calda-de-cafe',
        prepTime: '1h',
        servings: '12 fatias',
        ingredients: [
          'Bolo: 1 xícara de chocolate em pó, 1 xícara de açúcar, 2 ovos, 1 xícara de leite, 2 xícaras de farinha, 1 colher de fermento',
          'Calda: 1/2 xícara de café forte, 4 colheres de açúcar, 2 colheres de chocolate em pó',
        ],
        preparation: [
          'Prepare o bolo misturando os ingredientes e assando a 180°C.',
          'Para a calda, ferva todos os ingredientes por 5 minutos.',
          'Fure o bolo quente e despeje a calda por cima.',
        ],
      },
      {
        id: 'torta-mousse-de-cafe',
        name: 'Torta Mousse de Café',
        image: 'torta-mousse-de-cafe',
        prepTime: '30 min + 4h de geladeira',
        servings: '10 porções',
        ingredients: [
          'Base: 200g de biscoito de chocolate triturado com 100g de manteiga',
          'Mousse: 1 lata de leite condensado, 1 de creme de leite, 1 xícara de café forte, 1 gelatina sem sabor',
        ],
        preparation: [
          'Forre uma forma com a base de biscoito e reserve.',
          'Bata os ingredientes da mousse no liquidificador.',
          'Despeje sobre a base e leve para gelar por 4 horas.',
        ],
      },
      {
        id: 'bolo-de-fuba-com-cobertura-de-cafe',
        name: 'Bolo de Fubá com Cobertura de Café',
        image: 'bolo-de-fuba-com-cobertura-de-cafe',
        prepTime: '55 min',
        servings: '12 fatias',
        ingredients: [
          'Bolo: 2 xícaras de fubá, 1 xícara de farinha, 3 ovos, 1 xícara de leite, 1 xícara de óleo, 2 xícaras de açúcar, 1 colher de fermento',
          'Cobertura: 1 xícara de açúcar de confeiteiro, 3 colheres de sopa de café forte',
        ],
        preparation: [
          'Bata os ingredientes do bolo e asse a 180°C por 40 min.',
          'Misture os ingredientes da cobertura até virar um glacê.',
          'Despeje sobre o bolo morno.',
        ],
      },
      {
        id: 'torta-de-cafe-com-chantilly',
        name: 'Torta de Café com Chantilly',
        image: 'torta-de-cafe-com-chantilly',
        prepTime: '45 min + geladeira',
        servings: '8 porções',
        ingredients: [
          'Massa: 200g de farinha, 100g de manteiga, 50g de açúcar, 1 gema',
          'Recheio: Creme de confeiteiro de café',
          'Cobertura: Chantilly e raspas de chocolate',
        ],
        preparation: [
          'Faça a massa, forre uma forma e asse até dourar.',
          'Deixe esfriar, recheie com o creme de café.',
          'Cubra com chantilly e raspas de chocolate antes de servir.',
        ],
      },
      {
        id: 'cuca-de-cafe',
        name: 'Cuca de Café',
        image: 'cuca-de-cafe',
        prepTime: '1h',
        servings: '12 porções',
        ingredients: [
          'Massa: 3 xícaras de farinha, 2 xícaras de açúcar, 3 ovos, 1 xícara de leite com 1 colher de café solúvel, 1 colher de fermento',
          'Farofa: 1 xícara de farinha, 1 xícara de açúcar, 100g de manteiga, canela a gosto',
        ],
        preparation: [
          'Misture os ingredientes da massa e coloque em uma forma.',
          'Misture os ingredientes da farofa com os dedos e espalhe sobre a massa.',
          'Asse a 180°C por 40-50 minutos.',
        ],
      },
      {
        id: 'bolo-invertido-de-cafe-e-banana',
        name: 'Bolo Invertido de Café e Banana',
        image: 'bolo-invertido-de-cafe-e-banana',
        prepTime: '1h10',
        servings: '10 fatias',
        ingredients: [
          'Caramelo: 1 xícara de açúcar, 1/2 xícara de café forte',
          'Bananas fatiadas',
          'Massa de bolo de sua preferência (adicione café na massa)',
        ],
        preparation: [
          'Faça o caramelo de café no fundo da forma.',
          'Disponha as bananas fatiadas sobre o caramelo.',
          'Despeje a massa do bolo por cima.',
          'Asse conforme a receita da massa. Desenforme ainda morno.',
        ],
      },
    ],
  },
  {
    id: 'massas-receitas-salgadas-com-cafe',
    name: 'Massas & Receitas Salgadas',
    icon: UtensilsCrossed,
    recipes: [
      {
        id: 'risoto-de-cafe',
        name: 'Risoto de Café',
        image: 'risoto-de-cafe',
        prepTime: '30 min',
        servings: '2 porções',
        ingredients: [
          '1 xícara de arroz arbóreo',
          '1/2 cebola picada',
          '50 ml de café espresso',
          'Caldo de legumes quente',
          'Queijo parmesão ralado a gosto',
          'Manteiga e azeite',
        ],
        preparation: [
          'Refogue a cebola no azeite e manteiga. Adicione o arroz e frite um pouco.',
          'Adicione o café e mexa até evaporar.',
          'Vá adicionando o caldo de legumes aos poucos, mexendo sempre.',
          'Quando o arroz estiver al dente, finalize com manteiga e parmesão.',
        ],
      },
      {
        id: 'molho-barbecue-de-cafe',
        name: 'Molho Barbecue de Café',
        image: 'molho-barbecue-de-cafe',
        prepTime: '25 min',
        servings: 'Aprox. 300 ml',
        ingredients: [
          '1 xícara de ketchup',
          '1/4 xícara de café forte',
          '2 colheres de sopa de vinagre de maçã',
          '2 colheres de sopa de açúcar mascavo',
          '1 colher de chá de páprica defumada',
        ],
        preparation: [
          'Em uma panela, misture todos os ingredientes.',
          'Leve ao fogo baixo e cozinhe por cerca de 20 minutos, mexendo ocasionalmente, até o molho engrossar.',
          'Use para marinar carnes ou como acompanhamento.',
        ],
      },
      {
        id: 'costela-ao-molho-de-cafe',
        name: 'Costela Suína ao Molho de Café',
        image: 'costela-ao-molho-de-cafe',
        prepTime: '3h',
        servings: '4 porções',
        ingredients: [
          '1 kg de costela suína',
          'Marinada: 200ml de café forte, sal, pimenta, alho',
          'Molho: caldo do cozimento, 1 colher de amido de milho',
        ],
        preparation: [
          'Marine a costela por pelo menos 2 horas.',
          'Cozinhe na pressão por 40 minutos ou no forno coberta com alumínio por 2 horas.',
          'Retire a costela e engrosse o caldo do cozimento com amido para fazer o molho.',
          'Sirva a costela com o molho.',
        ],
      },
      {
        id: 'rub-de-cafe-para-carnes',
        name: 'Dry Rub de Café para Carnes',
        image: 'rub-de-cafe-para-carnes',
        prepTime: '5 min',
        servings: 'Aprox. 1/2 xícara',
        ingredients: [
          '3 colheres de sopa de café moído',
          '2 colheres de sopa de páprica defumada',
          '2 colheres de sopa de açúcar mascavo',
          '1 colher de sopa de sal',
          '1 colher de chá de pimenta preta',
        ],
        preparation: [
          'Misture todos os ingredientes.',
          'Esfregue generosamente na carne (bovina, suína ou frango) antes de grelhar ou assar.',
        ],
      },
      {
        id: 'vinagrete-de-cafe',
        name: 'Vinagrete de Café',
        image: 'vinagrete-de-cafe',
        prepTime: '5 min',
        servings: 'Aprox. 150ml',
        ingredients: [
          '100 ml de azeite de oliva',
          '30 ml de café espresso frio',
          '20 ml de vinagre balsâmico',
          '1 colher de chá de mostarda Dijon',
          'Sal e pimenta a gosto',
        ],
        preparation: [
          'Coloque todos os ingredientes em um pote com tampa.',
          'Agite vigorosamente até emulsionar.',
          'Ideal para saladas com folhas amargas e queijos fortes.',
        ],
      },
      {
        id: 'chilli-com-carne-e-cafe',
        name: 'Chilli com Carne e Café',
        image: 'chilli-com-carne-e-cafe',
        prepTime: '1h',
        servings: '6 porções',
        ingredients: [
          '500g de carne moída',
          '1 lata de feijão cozido',
          '1 lata de tomate pelado',
          '1 cebola picada',
          '100ml de café forte',
          'Pimenta e cominho a gosto',
        ],
        preparation: [
          'Refogue a carne e a cebola.',
          'Adicione o tomate, o café e os temperos.',
          'Cozinhe em fogo baixo por 45 minutos.',
          'Adicione o feijão e cozinhe por mais 10 minutos.',
        ],
      },
      {
        id: 'sopa-de-cebola-com-toque-de-cafe',
        name: 'Sopa de Cebola com Toque de Café',
        image: 'sopa-de-cebola-com-toque-de-cafe',
        prepTime: '50 min',
        servings: '4 porções',
        ingredients: [
          '4 cebolas grandes fatiadas',
          '1 litro de caldo de carne',
          '50ml de café coado',
          'Fatias de pão, queijo Gruyère ralado',
        ],
        preparation: [
          'Caramelize as cebolas lentamente na manteiga.',
          'Adicione o caldo e o café e cozinhe por 20 minutos.',
          'Sirva em cumbucas, cubra com uma fatia de pão e queijo.',
          'Gratine no forno.',
        ],
      },
      {
        id: 'file-mignon-ao-molho-de-cafe',
        name: 'Filé Mignon ao Molho de Café',
        image: 'file-mignon-ao-molho-de-cafe',
        prepTime: '25 min',
        servings: '2 porções',
        ingredients: [
          '2 medalhões de filé mignon',
          'Molho: 50ml de café espresso, 100ml de creme de leite, 1 dose de conhaque',
        ],
        preparation: [
          'Grelhe os medalhões no ponto desejado e reserve.',
          'Na mesma frigideira, deglaceie com o conhaque.',
          'Adicione o café e o creme de leite e reduza até engrossar.',
          'Sirva o molho sobre os medalhões.',
        ],
      },
      {
        id: 'cogumelos-salteados-com-cafe',
        name: 'Cogumelos Salteados com Café',
        image: 'cogumelos-salteados-com-cafe',
        prepTime: '15 min',
        servings: '2 porções',
        ingredients: [
          '300g de cogumelos variados',
          '2 dentes de alho picados',
          '30ml de café espresso',
          'Salsinha picada, sal, pimenta',
        ],
        preparation: [
          'Salteie o alho e os cogumelos em azeite quente.',
          'Quando dourados, adicione o café e deixe evaporar.',
          'Tempere com sal, pimenta e finalize com salsinha.',
        ],
      },
      {
        id: 'hamburguer-com-maionese-de-cafe',
        name: 'Hambúrguer com Maionese de Café',
        image: 'hamburguer-com-maionese-de-cafe',
        prepTime: '20 min',
        servings: '4 porções',
        ingredients: [
          '4 hambúrgueres',
          'Pão, queijo, alface, tomate',
          'Maionese: 1 xícara de maionese, 1 colher de sopa de café solúvel diluído',
        ],
        preparation: [
          'Misture a maionese com o café diluído até ficar homogêneo.',
          'Grelhe os hambúrgueres.',
          'Monte o lanche com a maionese especial de café.',
        ],
      },
    ],
  },
  {
    id: 'fitness-saudaveis-com-cafe',
    name: 'Fitness & Saudáveis com Café',
    icon: HeartPulse,
    recipes: [
      {
        id: 'smoothie-de-cafe-e-banana',
        name: 'Smoothie de Café e Banana',
        image: 'smoothie-de-cafe-e-banana',
        prepTime: '5 min',
        servings: '1 copo',
        ingredients: [
          '1 banana congelada',
          '100 ml de café forte, frio',
          '1/2 xícara de iogurte natural ou leite vegetal',
          '1 colher de sopa de sementes de chia',
        ],
        preparation: [
          'Bata todos os ingredientes no liquidificador até obter uma mistura cremosa.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'proteina-gelada-com-cafe',
        name: 'Proteína Gelada com Café',
        image: 'proteina-gelada-com-cafe',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: [
          '1 scoop de whey protein (sabor baunilha ou chocolate)',
          '150 ml de café forte, frio',
          'Gelo a gosto',
        ],
        preparation: [
          'Em uma coqueteleira ou liquidificador, misture o whey protein com o café frio.',
          'Adicione gelo e agite/bata bem até ficar homogêneo e gelado.',
        ],
      },
      {
        id: 'mingau-de-aveia-com-cafe',
        name: 'Mingau de Aveia com Café (Overnight Oats)',
        image: 'mingau-de-aveia-com-cafe',
        prepTime: '5 min + 8h de geladeira',
        servings: '1 porção',
        ingredients: [
          '1/2 xícara de aveia em flocos',
          '1/2 xícara de leite ou iogurte',
          '1/4 xícara de café coado frio',
          '1 colher de sopa de chia',
          'Adoçante a gosto',
        ],
        preparation: [
          'Misture todos os ingredientes em um pote de vidro.',
          'Deixe na geladeira durante a noite.',
          'Sirva frio na manhã seguinte, com frutas se desejar.',
        ],
      },
      {
        id: 'barrinha-de-proteina-e-cafe',
        name: 'Barrinha de Proteína e Café',
        image: 'barrinha-de-proteina-e-cafe',
        prepTime: '15 min + 1h de geladeira',
        servings: '8 barrinhas',
        ingredients: [
          '1 xícara de tâmaras sem caroço',
          '1 xícara de nozes ou amêndoas',
          '1/2 xícara de aveia',
          '2 scoops de whey protein de chocolate',
          '2 colheres de sopa de café forte',
        ],
        preparation: [
          'Processe as tâmaras e as nozes até formar uma pasta.',
          'Adicione os outros ingredientes e processe até misturar.',
          'Pressione a mistura em uma forma e leve à geladeira por 1 hora.',
          'Corte em barrinhas.',
        ],
      },
      {
        id: 'cafe-a-prova-de-balas-bulletproof',
        name: 'Café à Prova de Balas (Bulletproof)',
        image: 'cafe-a-prova-de-balas-bulletproof',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '250 ml de café de boa qualidade, quente',
          '1 colher de sopa de manteiga ghee',
          '1 colher de sopa de óleo de coco (ou TCM)',
        ],
        preparation: [
          'Prepare o café.',
          'No liquidificador, bata o café quente com a ghee e o óleo de coco até ficar cremoso e espumante.',
          'Beba imediatamente.',
        ],
      },
      {
        id: 'pudim-de-chia-com-cafe',
        name: 'Pudim de Chia com Café',
        image: 'pudim-de-chia-com-cafe',
        prepTime: '5 min + 4h de geladeira',
        servings: '2 porções',
        ingredients: [
          '1/4 xícara de sementes de chia',
          '1 xícara de leite de amêndoas',
          '1/4 xícara de café forte frio',
          '1 colher de sopa de xarope de ácer (maple syrup)',
        ],
        preparation: [
          'Misture todos os ingredientes em uma tigela.',
          'Deixe na geladeira por pelo menos 4 horas, ou até engrossar.',
          'Sirva com frutas vermelhas.',
        ],
      },
      {
        id: 'nice-cream-de-cafe',
        name: '"Nice Cream" de Café',
        image: 'nice-cream-de-cafe',
        prepTime: '5 min',
        servings: '2 porções',
        ingredients: [
          '2 bananas maduras congeladas em rodelas',
          '1 colher de sopa de café solúvel',
          '1 colher de sopa de leite vegetal (se necessário)',
        ],
        preparation: [
          'Bata as bananas congeladas e o café em um processador de alimentos até obter uma consistência de sorvete.',
          'Adicione o leite se precisar de ajuda para bater.',
          'Sirva imediatamente.',
        ],
      },
      {
        id: 'muffins-fit-de-cafe-e-cacau',
        name: 'Muffins Fit de Café e Cacau',
        image: 'muffins-fit-de-cafe-e-cacau',
        prepTime: '30 min',
        servings: '12 muffins',
        ingredients: [
          '1 xícara de farinha de aveia',
          '2 ovos',
          '1/2 xícara de iogurte grego',
          '1/2 xícara de café forte',
          '1/4 xícara de cacau em pó',
          'Adoçante a gosto',
          '1 colher de chá de fermento',
        ],
        preparation: [
          'Misture os ingredientes úmidos e depois adicione os secos.',
          'Distribua em forminhas de muffin.',
          'Asse a 180°C por 15-20 minutos.',
        ],
      },
      {
        id: 'bolinhas-energeticas-de-cafe',
        name: 'Bolinhas Energéticas de Café',
        image: 'bolinhas-energeticas-de-cafe',
        prepTime: '10 min',
        servings: '15 bolinhas',
        ingredients: [
          '1 xícara de aveia',
          '1/2 xícara de pasta de amendoim',
          '1/3 xícara de mel',
          '1 colher de sopa de café moído',
          '1/2 xícara de gotas de chocolate amargo',
        ],
        preparation: [
          'Misture todos os ingredientes.',
          'Faça bolinhas com as mãos.',
          'Guarde na geladeira.',
        ],
      },
      {
        id: 'crepioca-de-cafe',
        name: 'Crepioca de Café',
        image: 'crepioca-de-cafe',
        prepTime: '7 min',
        servings: '1 porção',
        ingredients: [
          '1 ovo',
          '2 colheres de sopa de goma de tapioca',
          '1 colher de chá de café solúvel',
          'Recheio a gosto (ex: pasta de amendoim, banana)',
        ],
        preparation: [
          'Misture bem o ovo, a goma e o café.',
          'Despeje em uma frigideira antiaderente quente.',
          'Cozinhe dos dois lados.',
          'Recheie e dobre.',
        ],
      },
    ],
  },
  {
    id: 'drinks-coqueteis-com-cafe',
    name: 'Drinks & Coquetéis com Café',
    icon: Martini,
    recipes: [
      {
        id: 'espresso-martini',
        name: 'Espresso Martini',
        image: 'espresso-martini',
        prepTime: '5 min',
        servings: '1 taça',
        ingredients: [
          '50 ml de vodka',
          '30 ml de licor de café (Kahlúa)',
          '30 ml de café espresso recém-extraído',
          'Gelo',
          'Grãos de café para decorar',
        ],
        preparation: [
          'Encha uma coqueteleira com gelo.',
          'Adicione a vodka, o licor de café e o espresso.',
          'Agite vigorosamente por 15 segundos.',
          'Coe para uma taça de martini gelada e decore com grãos de café.',
        ],
      },
      {
        id: 'irish-coffee',
        name: 'Irish Coffee',
        image: 'irish-coffee',
        prepTime: '7 min',
        servings: '1 taça',
        ingredients: [
          '40 ml de uísque irlandês',
          '1 colher de chá de açúcar mascavo',
          '120 ml de café quente e forte',
          'Creme de leite fresco, levemente batido',
        ],
        preparation: [
          'Aqueça uma taça de vidro com água quente e descarte a água.',
          'Adicione o uísque e o açúcar, mexendo para dissolver.',
          'Despeje o café quente.',
          'Com cuidado, despeje o creme de leite levemente batido sobre as costas de uma colher para que flutue no topo.',
        ],
      },
      {
        id: 'black-russian',
        name: 'Black Russian',
        image: 'black-russian',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: ['50 ml de vodka', '20 ml de licor de café', 'Gelo'],
        preparation: [
          'Encha um copo baixo (old fashioned) com gelo.',
          'Adicione a vodka e o licor de café.',
          'Mexa suavemente e sirva.',
        ],
      },
      {
        id: 'white-russian',
        name: 'White Russian',
        image: 'white-russian',
        prepTime: '4 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de vodka',
          '20 ml de licor de café',
          '30 ml de creme de leite fresco (ou leite)',
          'Gelo',
        ],
        preparation: [
          'Siga a receita do Black Russian.',
          'No final, despeje o creme de leite sobre a bebida para que ele flutue.',
          'Mexa antes de beber, se preferir.',
        ],
      },
      {
        id: 'revolver-cocktail',
        name: 'Revolver Cocktail',
        image: 'revolver-cocktail',
        prepTime: '4 min',
        servings: '1 taça',
        ingredients: [
          '60 ml de bourbon',
          '15 ml de licor de café',
          '2 lances de orange bitters',
          'Casca de laranja para decorar',
        ],
        preparation: [
          'Gele uma taça coupé.',
          'Em um mixing glass com gelo, adicione o bourbon, o licor e os bitters.',
          'Mexa bem até gelar.',
          'Coe para a taça gelada e decore torcendo uma casca de laranja sobre o drink.',
        ],
      },
      {
        id: 'carajillo',
        name: 'Carajillo',
        image: 'carajillo',
        prepTime: '5 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de Licor 43',
          '50 ml de café espresso quente',
          'Gelo',
        ],
        preparation: [
          'Encha um copo baixo com gelo.',
          'Despeje o Licor 43.',
          'Extraia o espresso e despeje sobre o licor e o gelo.',
          'Mexa para misturar.',
        ],
      },
      {
        id: 'negroni-com-cafe',
        name: 'Negroni com Infusão de Café',
        image: 'negroni-com-cafe',
        prepTime: '5 min (+ infusão)',
        servings: '1 copo',
        ingredients: [
          '30 ml de gin',
          '30 ml de Campari com infusão de café*',
          '30 ml de vermute tinto',
        ],
        preparation: [
          '*Para a infusão: adicione 1 colher de sopa de grãos de café ao Campari por 24h e depois coe.',
          'Em um copo com gelo, adicione todos os ingredientes.',
          'Mexa e decore com uma fatia de laranja.',
        ],
      },
      {
        id: 'cold-brew-gin-tonica',
        name: 'Cold Brew Gin & Tônica',
        image: 'cold-brew-gin-tonica',
        prepTime: '4 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de gin',
          '30 ml de cold brew',
          '120 ml de água tônica',
          'Gelo e limão',
        ],
        preparation: [
          'Encha um copo alto com gelo.',
          'Adicione o gin e o cold brew.',
          'Complete com água tônica.',
          'Decore com uma fatia de limão.',
        ],
      },
      {
        id: 'old-fashioned-de-cafe',
        name: 'Old Fashioned de Café',
        image: 'old-fashioned-de-cafe',
        prepTime: '6 min',
        servings: '1 copo',
        ingredients: [
          '60 ml de rye whiskey ou bourbon',
          '1 colher de chá de xarope de café*',
          '2 lances de Angostura bitters',
        ],
        preparation: [
          '*Xarope: ferva partes iguais de café e açúcar até dissolver.',
          'Em um copo baixo, adicione o xarope e os bitters.',
          'Adicione uma pedra grande de gelo e o whiskey.',
          'Mexa e decore com uma casca de laranja.',
        ],
      },
      {
        id: 'batida-de-cafe',
        name: 'Batida de Café',
        image: 'batida-de-cafe',
        prepTime: '5 min',
        servings: '2 copos',
        ingredients: [
          '100 ml de cachaça',
          '100 ml de café coado forte',
          '1/2 lata de leite condensado',
          'Gelo',
        ],
        preparation: [
          'Bata todos os ingredientes no liquidificador.',
          'Sirva em copos com mais gelo se desejar.',
        ],
      },
    ],
  },
];

export const getRecipeById = (id: string) => {
  for (const category of categories) {
    const recipe = category.recipes.find(recipe => recipe.id === id);
    if (recipe) {
      return recipe;
    }
  }
  return null;
};
