
import type { Category } from './types';
import {
  Coffee,
  IceCream,
  Waves,
  Blend,
  Sparkles,
  CakeSlice,
  Cake,
  UtensilsCrossed,
  HeartPulse,
  Martini,
} from 'lucide-react';

export const categories: Category[] = [
  {
    id: 'classicos-do-cafe',
    name: 'Clássicos do Café',
    icon: Coffee,
    recipes: [
      {
        id: 'cappuccino-tradicional',
        name: 'Cappuccino Tradicional',
        image: 'cappuccino-tradicional',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso forte',
          '120 ml de leite vaporizado',
          '2 colheres de sopa de espuma de leite',
          '1 colher de chá de cacau em pó (opcional)',
        ],
        preparation: [
          'Primeiramente, extraia um espresso forte de 30 ml diretamente em sua xícara de cappuccino preferida.',
          'Em seguida, vaporize 120 ml de leite integral até que ele atinja uma textura cremosa e uma espuma densa no topo. A temperatura ideal é entre 65-70°C.',
          'Incline a xícara e despeje o leite vaporizado sobre o espresso, usando uma colher para segurar a espuma mais espessa no início.',
          'Finalize adicionando a espuma restante no topo da bebida, formando uma cúpula branca.',
          'Para um toque especial, polvilhe uma fina camada de cacau em pó sobre a espuma antes de servir.',
        ],
      },
      {
        id: 'espresso-macchiato',
        name: 'Espresso Macchiato',
        image: 'espresso-macchiato',
        prepTime: '3 min',
        servings: '1 xícara pequena',
        ingredients: [
          '30 ml de café espresso',
          '1 colher de sopa de espuma de leite',
        ],
        preparation: [
          'Extraia um shot de 30 ml de espresso diretamente em uma xícara pequena de vidro ou cerâmica (demitasse).',
          'Com uma colher, adicione cuidadosamente uma pequena quantidade de espuma de leite bem densa no centro do espresso.',
          'A "mancha" (macchia) de leite deve ficar visível na superfície da crema do café.',
          'Sirva imediatamente para apreciar o contraste de temperatura e textura.',
        ],
      },
      {
        id: 'cafe-latte',
        name: 'Café Latte',
        image: 'cafe-latte',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '180 ml de leite vaporizado',
          'Fina camada de espuma de leite',
        ],
        preparation: [
          'Extraia um shot de 30 ml de espresso em uma xícara ou copo grande (aproximadamente 240 ml).',
          'Vaporize 180 ml de leite até que fique cremoso e aveludado, com uma fina camada de microespuma no topo.',
          'Despeje o leite vaporizado sobre o espresso, criando uma bebida homogênea e cremosa.',
          'Se tiver habilidade, este é o momento ideal para praticar sua latte art!',
        ],
      },
      {
        id: 'americano',
        name: 'Americano',
        image: 'americano',
        prepTime: '2 min',
        servings: '1 xícara',
        ingredients: ['30 ml de café espresso', '150 ml de água quente'],
        preparation: [
          'Aqueça 150 ml de água a uma temperatura de aproximadamente 90-94°C e despeje na xícara.',
          'Em seguida, extraia um shot de 30 ml de espresso diretamente sobre a água quente.',
          'Essa ordem é crucial para preservar a crema do espresso na superfície da bebida, resultando em mais aroma e sabor.',
        ],
      },
      {
        id: 'mocha',
        name: 'Mocha',
        image: 'mocha',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '30 ml de calda de chocolate de boa qualidade',
          '150 ml de leite vaporizado',
          'Chantilly e raspas de chocolate (opcional)',
        ],
        preparation: [
          'Despeje a calda de chocolate no fundo de uma xícara grande ou copo de vidro.',
          'Extraia um shot de espresso diretamente sobre a calda.',
          'Misture bem até que o chocolate esteja completamente dissolvido no café.',
          'Vaporize o leite e despeje sobre a mistura de café com chocolate.',
          'Se desejar, finalize com uma generosa porção de chantilly e decore com raspas de chocolate.',
        ],
      },
      {
        id: 'ristretto',
        name: 'Ristretto',
        image: 'ristretto',
        prepTime: '2 min',
        servings: '1 xícara pequena',
        ingredients: ['20 ml de café espresso (extração curta)'],
        preparation: [
          'Use a mesma quantidade de pó de café de um espresso normal, mas interrompa a extração mais cedo, em cerca de 15-20 segundos.',
          'O resultado será um shot de 20 ml, mais concentrado, menos amargo e com doçura e acidez acentuadas.',
          'Sirva em uma xícara de espresso e aprecie a complexidade dos sabores.',
        ],
      },
      {
        id: 'espresso-panna',
        name: 'Espresso con Panna',
        image: 'espresso-panna',
        prepTime: '4 min',
        servings: '1 xícara pequena',
        ingredients: ['30 ml de café espresso', 'Chantilly fresco a gosto'],
        preparation: [
          'Extraia um shot de espresso em uma xícara pequena.',
          'Imediatamente, adicione uma ou duas colheradas de chantilly fresco e levemente adocicado por cima.',
          'O contraste do café quente com o chantilly frio e cremoso é a essência desta bebida. Sirva na hora.',
        ],
      },
      {
        id: 'doppio',
        name: 'Doppio (Espresso Duplo)',
        image: 'doppio',
        prepTime: '3 min',
        servings: '1 xícara',
        ingredients: ['60 ml de café espresso'],
        preparation: [
          'Utilize um porta-filtro duplo na sua máquina de espresso, com aproximadamente 14-18g de café moído.',
          'Extraia um shot duplo, resultando em 60 ml de bebida em cerca de 25-30 segundos.',
          'Sirva em uma xícara de cappuccino para permitir que os aromas se expandam e sejam mais bem apreciados.',
        ],
      },
      {
        id: 'cafe-bombeado',
        name: 'Café Bombeado (Prensa Francesa)',
        image: 'cafe-bombeado',
        prepTime: '6 min',
        servings: '2 xícaras',
        ingredients: ['30g de café moído grosseiramente', '500 ml de água quente (não fervente)'],
        preparation: [
          'Escalde o cilindro da prensa francesa com água quente para pré-aquecer o equipamento e depois descarte a água.',
          'Adicione o café com moagem grossa (aspecto de areia de praia) no fundo da prensa.',
          'Despeje a água quente (aprox. 92-96°C) sobre o pó, garantindo que todo o café seja umedecido. Mexa levemente.',
          'Coloque a tampa com o êmbolo levantado e aguarde 4 minutos para a infusão.',
          'Após o tempo, pressione o êmbolo de forma lenta e constante até o final. Sirva imediatamente para evitar super-extração.',
        ],
      },
      {
        id: 'aeropress-classico',
        name: 'Aeropress Clássico',
        image: 'aeropress-classico',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: ['17g de café moído médio-fino', '250 ml de água quente'],
        preparation: [
          'Monte o Aeropress no método tradicional (sobre a xícara), com o filtro de papel previamente escaldado.',
          'Adicione o café moído (textura parecida com sal de cozinha).',
          'Inicie o cronômetro e despeje 250 ml de água quente (85-90°C) sobre o café.',
          'Mexa por cerca de 10 segundos e insira o êmbolo para criar um vácuo e interromper o gotejamento.',
          'Quando o cronômetro atingir 1 minuto e 30 segundos, pressione o êmbolo suavemente por 20-30 segundos até ouvir um chiado.',
        ],
      },
    ],
  },
  {
    id: 'cafes-gelados-refrescantes',
    name: 'Cafés Gelados & Refrescantes',
    icon: IceCream,
    recipes: [
      {
        id: 'iced-caramel-latte',
        name: 'Iced Caramel Latte',
        image: 'iced-caramel-latte',
        prepTime: '5 min',
        servings: '1 copo grande',
        ingredients: [
          '50 ml de café espresso',
          '150 ml de leite frio',
          '2 colheres de sopa de calda de caramelo',
          'Gelo a gosto',
          'Chantilly (opcional)',
        ],
        preparation: [
          'Decore as paredes internas de um copo alto com uma colher de sopa de calda de caramelo.',
          'Encha completamente o copo com cubos de gelo.',
          'Despeje o leite frio sobre o gelo.',
          'Em uma xícara separada, misture o espresso recém-extraído com a outra colher de sopa de calda de caramelo até dissolver.',
          'Despeje lentamente a mistura de café com caramelo sobre o leite.',
          'Se desejar, finalize com chantilly e um fio extra de caramelo por cima.',
        ],
      },
      {
        id: 'cold-brew',
        name: 'Cold Brew',
        image: 'cold-brew',
        prepTime: '12 horas',
        servings: 'Aprox. 750 ml',
        ingredients: [
          '100g de café em grãos moído grosseiramente',
          '1 litro de água filtrada fria',
        ],
        preparation: [
          'Em um recipiente grande com tampa (como uma jarra), combine o café moído grosseiramente com a água fria.',
          'Mexa suavemente para garantir que todo o pó esteja em contato com a água.',
          'Tampe o recipiente e deixe em infusão na geladeira por um período de 12 a 24 horas, dependendo da intensidade desejada.',
          'Após a infusão, coe a mistura lentamente usando um filtro de pano ou papel para remover todos os resíduos de café.',
          'O concentrado de cold brew está pronto. Sirva em um copo com gelo, diluindo com água ou leite a gosto (geralmente na proporção 1:1 ou 1:2).',
        ],
      },
      {
        id: 'espresso-tonica',
        name: 'Espresso Tônica',
        image: 'espresso-tonica',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de café espresso',
          '150 ml de água tônica de boa qualidade',
          'Gelo a gosto',
          '1 fatia de limão ou laranja para decorar',
        ],
        preparation: [
          'Gele bem o copo e a água tônica.',
          'Encha um copo alto (long drink) com bastante gelo.',
          'Despeje a água tônica gelada sobre o gelo.',
          'Extraia um espresso duplo e, com cuidado, despeje-o lentamente sobre a tônica para criar um efeito visual em camadas.',
          'Finalize decorando com uma fatia ou zest de limão ou laranja, que adicionará um aroma cítrico refrescante.',
        ],
      },
      {
        id: 'frappuccino-caramelo',
        name: 'Frappuccino de Caramelo',
        image: 'frappuccino-caramelo',
        prepTime: '8 min',
        servings: '1 copo grande',
        ingredients: [
          '50 ml de café forte frio',
          '100 ml de leite',
          '2 colheres de sopa de calda de caramelo',
          '1 xícara de gelo',
          'Chantilly para decorar',
        ],
        preparation: [
          'Em um liquidificador, adicione o café frio, o leite, uma colher de sopa da calda de caramelo e a xícara de gelo.',
          'Bata em alta velocidade até que a mistura fique homogênea e com a consistência de um milk-shake.',
          'Decore a parte interna do copo com a outra colher de calda de caramelo.',
          'Despeje a bebida batida no copo decorado.',
          'Cubra com chantilly e, se quiser, regue com mais um fio de calda de caramelo.',
        ],
      },
      {
        id: 'iced-americano',
        name: 'Iced Americano',
        image: 'iced-americano',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: ['60 ml de café espresso', '120 ml de água fria', 'Gelo a gosto'],
        preparation: [
          'Encha um copo completamente com gelo para manter a bebida gelada por mais tempo.',
          'Adicione 120 ml de água fria sobre o gelo.',
          'Extraia um espresso duplo e despeje-o diretamente sobre a água gelada.',
          'Aprecie a bebida assim ou mexa suavemente para incorporar.',
        ],
      },
      {
        id: 'affogato',
        name: 'Affogato',
        image: 'affogato',
        prepTime: '3 min',
        servings: '1 porção',
        ingredients: ['1 bola de sorvete de baunilha de alta qualidade', '30 ml de café espresso quente'],
        preparation: [
          'Coloque uma bola generosa de sorvete de baunilha (ou fior di latte) em uma taça de sobremesa ou xícara de vidro pré-resfriada.',
          'Imediatamente antes de servir, extraia um shot de espresso quente e vibrante.',
          'Despeje o espresso quente diretamente sobre a bola de sorvete.',
          'A sobremesa deve ser servida na hora, para que se possa apreciar o contraste do quente e frio, doce e amargo. Coma com uma colher!',
        ],
      },
      {
        id: 'cold-brew-com-leite-de-coco',
        name: 'Cold Brew com Leite de Coco',
        image: 'cold-brew-com-leite-de-coco',
        prepTime: '5 min (+ infusão)',
        servings: '1 copo',
        ingredients: [
          '150 ml de concentrado de cold brew',
          '50 ml de leite de coco cremoso',
          'Gelo a gosto',
          'Flocos de coco queimado para decorar (opcional)',
        ],
        preparation: [
          'Encha um copo alto com gelo.',
          'Adicione o concentrado de cold brew.',
          'Despeje o leite de coco por cima, que irá se misturar lentamente criando um efeito bonito.',
          'Se desejar, decore com flocos de coco queimado para um sabor e textura extras.',
        ],
      },
      {
        id: 'limonada-com-cafe',
        name: 'Limonada com Café',
        image: 'limonada-com-cafe',
        prepTime: '7 min',
        servings: '1 copo',
        ingredients: [
          '100 ml de limonada suíça (feita com limão e um pouco da casca, batida com água e açúcar)',
          '50 ml de café coado forte e frio',
          'Gelo a gosto',
          'Folhas de hortelã para decorar',
        ],
        preparation: [
          'Encha um copo com bastante gelo.',
          'Despeje a limonada fresca até um pouco mais da metade do copo.',
          'Com cuidado, usando as costas de uma colher, despeje lentamente o café frio para que ele forme uma camada superior.',
          'Decore com um ramo de hortelã fresco antes de servir. O contraste surpreende!',
        ],
      },
      {
        id: 'shakerato',
        name: 'Shakerato',
        image: 'shakerato',
        prepTime: '4 min',
        servings: '1 taça',
        ingredients: [
          '60 ml de café espresso',
          '1 colher de chá de açúcar (ou xarope simples)',
          'Gelo',
        ],
        preparation: [
          'Resfrie uma taça de martini ou coupé no freezer.',
          'Encha uma coqueteleira com 5 a 6 cubos de gelo.',
          'Extraia o espresso e adicione-o imediatamente na coqueteleira, junto com o açúcar.',
          'Feche bem e agite vigorosamente por cerca de 15 a 20 segundos. Você sentirá a coqueteleira ficar extremamente fria.',
          'Coe a bebida para a taça gelada, descartando o gelo. Uma espuma densa e dourada deve se formar no topo.',
        ],
      },
      {
        id: 'iced-mocha-branco',
        name: 'Iced Mocha Branco',
        image: 'iced-mocha-branco',
        prepTime: '6 min',
        servings: '1 copo grande',
        ingredients: [
          '30g de chocolate branco de boa qualidade, picado',
          '60 ml de café espresso quente',
          '120 ml de leite frio',
          'Gelo a gosto',
        ],
        preparation: [
          'Em uma xícara, coloque o chocolate branco picado.',
          'Extraia o espresso quente sobre o chocolate e mexa bem com um pequeno batedor até que o chocolate esteja completamente derretido e a mistura homogênea.',
          'Encha um copo grande com gelo.',
          'Despeje a mistura de café com chocolate sobre o gelo.',
          'Complete o copo com o leite frio e mexa bem para incorporar todos os sabores.',
        ],
      },
    ],
  },
  {
    id: 'cafes-cremosos-espumados',
    name: 'Cafés Cremosos & Espumados',
    icon: Waves,
    recipes: [
      {
        id: 'flat-white',
        name: 'Flat White',
        image: 'flat-white',
        prepTime: '4 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de café espresso (duplo)',
          '120 ml de leite vaporizado com microespuma',
        ],
        preparation: [
          'Extraia um espresso duplo diretamente em uma xícara de cerâmica (aproximadamente 180ml).',
          'Vaporize o leite até obter uma textura sedosa e brilhante, com uma microespuma fina, sem bolhas grandes. A temperatura ideal é 65°C.',
          'Despeje o leite sobre o espresso de forma contínua e controlada, permitindo que o leite se misture com o café e a microespuma forme uma fina camada branca no topo.',
          'O resultado é uma bebida mais forte e intensa em sabor de café do que um latte, com uma textura aveludada.',
        ],
      },
      {
        id: 'cafe-au-lait',
        name: 'Café au Lait',
        image: 'cafe-au-lait',
        prepTime: '5 min',
        servings: '1 xícara grande',
        ingredients: [
          '120 ml de café forte coado (preferencialmente em método de infusão, como prensa francesa)',
          '120 ml de leite aquecido',
        ],
        preparation: [
          'Prepare um café coado forte. A proporção de 1:1 é a chave aqui.',
          'Aqueça o leite em uma panela ou no micro-ondas até que esteja quente, mas sem ferver (cerca de 70°C).',
          'Sirva em uma tigela ou xícara grande, despejando o café e o leite quente simultaneamente de lados opostos da xícara para uma mistura perfeita.',
        ],
      },
      {
        id: 'latte-macchiato',
        name: 'Latte Macchiato',
        image: 'latte-macchiato',
        prepTime: '6 min',
        servings: '1 copo de vidro',
        ingredients: [
          '200 ml de leite vaporizado',
          '30 ml de café espresso',
        ],
        preparation: [
          'Vaporize o leite criando uma quantidade generosa de espuma.',
          'Despeje o leite e a espuma em um copo alto de vidro e espere cerca de 30 segundos para que o leite e a espuma se separem, formando duas camadas distintas.',
          'Extraia o espresso.',
          'Despeje o espresso lentamente e com cuidado bem no centro da espuma. O café, mais denso que a espuma mas menos denso que o leite, formará uma terceira camada no meio.',
          'Aprecie as belas camadas antes de misturar (ou não!).',
        ],
      },
      {
        id: 'cappuccino-vienense',
        name: 'Cappuccino Vienense',
        image: 'cappuccino-vienense',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de café espresso duplo',
          'Chantilly fresco e adocicado',
          'Raspas de chocolate ou cacau em pó',
        ],
        preparation: [
          'Extraia um espresso duplo em uma xícara ou copo de vidro.',
          'Em vez de leite vaporizado, cubra generosamente a superfície do café com chantilly fresco.',
          'A ideia é criar um "chapéu" de chantilly sobre o café quente.',
          'Decore com raspas de chocolate amargo ou polvilhe cacau em pó por cima para um toque final elegante.',
        ],
      },
      {
        id: 'cortado',
        name: 'Cortado',
        image: 'cortado',
        prepTime: '3 min',
        servings: '1 copo pequeno',
        ingredients: [
          '30 ml de café espresso',
          '30 ml de leite vaporizado',
        ],
        preparation: [
          'Extraia um shot de espresso em um copo de vidro pequeno (aproximadamente 90-120 ml).',
          'Vaporize uma pequena quantidade de leite apenas para dar cremosidade, com pouquíssima espuma.',
          'Despeje o leite sobre o espresso na proporção de 1:1. O objetivo é "cortar" a intensidade do espresso, suavizando sua acidez sem mascarar o sabor.',
          'A bebida deve ser equilibrada e servida morna.',
        ],
      },
      {
        id: 'dalgona-coffee',
        name: 'Dalgona Coffee',
        image: 'dalgona-coffee',
        prepTime: '10 min',
        servings: '1 copo',
        ingredients: [
          '2 colheres de sopa de café solúvel',
          '2 colheres de sopa de açúcar',
          '2 colheres de sopa de água quente',
          '200 ml de leite frio ou quente',
        ],
        preparation: [
          'Em uma tigela, combine o café solúvel, o açúcar e a água quente.',
          'Com um batedor de arame (fouet) ou um mixer elétrico, bata a mistura vigorosamente por vários minutos, até que ela se transforme em um creme espesso, fofo e de cor clara (caramelo).',
          'Encha um copo com gelo (se for a versão fria) e leite.',
          'Deposite o creme de café por cima do leite e sirva. Mexa antes de beber.',
        ],
      },
      {
        id: 'magic-coffee',
        name: 'Magic Coffee',
        image: 'magic-coffee',
        prepTime: '4 min',
        servings: '1 xícara pequena',
        ingredients: ['30 ml de ristretto duplo', '90 ml de leite vaporizado'],
        preparation: [
          'Extraia um ristretto duplo (um shot duplo, mas com extração mais curta) em uma xícara de cappuccino de 150 ml.',
          'Vaporize o leite até obter uma textura perfeitamente sedosa e brilhante, ideal para latte art.',
          'Despeje o leite sobre o ristretto. A proporção de café para leite é maior que a de um flat white, resultando em um sabor de café pronunciado, porém equilibrado pela doçura do leite.',
        ],
      },
      {
        id: 'cafe-breve',
        name: 'Café Breve',
        image: 'cafe-breve',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: ['60 ml de café espresso', '120 ml de "half-and-half" vaporizado'],
        preparation: [
          'O "half-and-half" é uma mistura meio a meio de leite integral e creme de leite, resultando em uma bebida mais rica e cremosa.',
          'Extraia um espresso duplo em uma xícara de cappuccino.',
          'Vaporize a mistura de leite e creme até ficar quente e espumosa.',
          'Despeje sobre o espresso como faria com um cappuccino. A espuma será mais densa e rica.',
        ],
      },
      {
        id: 'piccolo-latte',
        name: 'Piccolo Latte',
        image: 'piccolo-latte',
        prepTime: '4 min',
        servings: '1 copo pequeno',
        ingredients: ['30 ml de ristretto', '60-90 ml de leite vaporizado'],
        preparation: [
          'Extraia um shot de ristretto em um copo de vidro pequeno ou demitasse (90-100ml).',
          'Vaporize o leite até obter uma textura aveludada e cremosa, como para um latte.',
          'Despeje o leite sobre o ristretto, preenchendo o copo.',
          'É basicamente um "baby latte", perfeito para quem quer o sabor de um latte com menos volume de leite e mais intensidade de café.',
        ],
      },
      {
        id: 'mel-com-cafe',
        name: 'Mel com Café e Espuma',
        image: 'mel-com-cafe',
        prepTime: '6 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '1 colher de sopa de mel de boa qualidade',
          '150 ml de leite vaporizado',
          'Canela em pó para decorar',
        ],
        preparation: [
          'Coloque o mel no fundo da sua xícara preferida.',
          'Extraia o shot de espresso diretamente sobre o mel. Mexa bem para garantir que o mel se dissolva completamente.',
          'Vaporize o leite até ficar cremoso e com uma boa camada de espuma.',
          'Despeje o leite sobre a mistura de café e mel.',
          'Finalize polvilhando um pouco de canela em pó sobre a espuma.',
        ],
      },
    ],
  },
  {
    id: 'cremes-pastas-de-cafe',
    name: 'Cremes & Pastas de Café',
    icon: Blend,
    recipes: [
      {
        id: 'creme-de-cafe',
        name: 'Creme de Café',
        image: 'creme-de-cafe',
        prepTime: '10 min',
        servings: '4 porções',
        ingredients: [
          '1 xícara de açúcar',
          '50g de café solúvel de boa qualidade',
          '1 xícara de água fervente',
        ],
        preparation: [
          'Na tigela de uma batedeira, coloque o açúcar e o café solúvel.',
          'Com a batedeira em velocidade baixa, adicione cuidadosamente a água fervente.',
          'Aumente a velocidade para alta e bata por aproximadamente 10 a 15 minutos. A mistura vai se transformar em um creme muito fofo, volumoso e de cor clara.',
          'Transfira o creme para um pote com tampa e guarde no freezer. Ele não congela completamente, mantendo a textura cremosa. Sirva uma colherada em uma xícara de leite quente ou frio.',
        ],
      },
      {
        id: 'pasta-de-amendoim-com-cafe',
        name: 'Pasta de Amendoim com Café',
        image: 'pasta-de-amendoim-com-cafe',
        prepTime: '8 min',
        servings: 'Aprox. 200g',
        ingredients: [
          '150g de pasta de amendoim integral sem açúcar',
          '1 colher de sopa de café solúvel em pó fino',
          '1 colher de sopa de mel, agave ou maple syrup',
          '1 pitada de sal (se a pasta não tiver)',
        ],
        preparation: [
          'Em uma tigela, coloque a pasta de amendoim.',
          'Adicione o café solúvel, o mel (ou outro adoçante) e a pitada de sal.',
          'Com uma espátula ou colher, misture vigorosamente até que todos os ingredientes estejam completamente incorporados e a pasta fique homogênea.',
          'Experimente e ajuste a doçura ou a intensidade do café, se necessário. Excelente para comer com pães, torradas, frutas ou como ingrediente em outras receitas.',
        ],
      },
      {
        id: 'ganache-de-cafe',
        name: 'Ganache de Café',
        image: 'ganache-de-cafe',
        prepTime: '10 min',
        servings: 'Aprox. 300ml',
        ingredients: [
          '200g de chocolate meio amargo (50-60% cacau), picado',
          '100g de creme de leite (com pelo menos 35% de gordura)',
          '1 colher de sopa de café solúvel (ou 30ml de espresso forte)',
        ],
        preparation: [
          'Coloque o chocolate picado em uma tigela resistente ao calor.',
          'Em uma panela pequena, aqueça o creme de leite com o café solúvel até que o café se dissolva e o creme comece a soltar bolhas nas laterais (não deixe ferver).',
          'Despeje o creme quente sobre o chocolate picado e deixe descansar por 2-3 minutos sem mexer, para que o calor derreta o chocolate.',
          'Após o tempo de espera, misture suavemente do centro para fora com uma espátula até obter uma emulsão lisa, brilhante e homogênea.',
          'Use como cobertura ou recheio para bolos, tortas e sobremesas.',
        ],
      },
      {
        id: 'manteiga-de-cafe',
        name: 'Manteiga Aromatizada de Café',
        image: 'manteiga-de-cafe',
        prepTime: '10 min',
        servings: 'Aprox. 100g',
        ingredients: [
          '100g de manteiga sem sal em temperatura ambiente',
          '1 colher de chá de café moído finamente (não solúvel)',
          '1 colher de chá de açúcar de confeiteiro',
          '1/4 colher de chá de extrato de baunilha (opcional)',
        ],
        preparation: [
          'Em uma tigela, use uma espátula ou batedeira para bater a manteiga até que ela fique bem macia e pálida.',
          'Adicione o café moído fino, o açúcar de confeiteiro e a baunilha.',
          'Misture tudo muito bem até que os ingredientes estejam uniformemente distribuídos.',
          'Coloque a manteiga sobre um pedaço de papel manteiga, enrole formando um cilindro e torça as pontas. Leve à geladeira para firmar.',
          'Sirva fatias sobre panquecas, waffles, pães ou um bife grelhado.',
        ],
      },
      {
        id: 'doce-de-leite-com-cafe',
        name: 'Doce de Leite com Café',
        image: 'doce-de-leite-com-cafe',
        prepTime: '5 min',
        servings: 'Aprox. 400g',
        ingredients: [
          '1 lata (395g) de doce de leite cremoso de boa qualidade',
          '2 colheres de chá de café solúvel em pó',
          '1 colher de sopa de creme de leite (opcional, para diluir)',
        ],
        preparation: [
          'Em uma tigela, coloque o doce de leite.',
          'Polvilhe o café solúvel por cima e comece a misturar com uma colher ou espátula.',
          'Continue mexendo até que o pó de café esteja completamente dissolvido e a cor do doce de leite esteja uniforme.',
          'Se desejar uma consistência mais fluida, adicione o creme de leite e misture bem. Perfeito para rechear churros, bolos ou comer puro.',
        ],
      },
      {
        id: 'geleia-de-cafe',
        name: 'Geleia de Café',
        image: 'geleia-de-cafe',
        prepTime: '25 min',
        servings: 'Aprox. 250ml',
        ingredients: [
          '250 ml de café forte coado',
          '200g de açúcar cristal',
          '1 colher de sopa de suco de limão',
          '1/2 pacote de pectina em pó (ou siga a instrução da embalagem)',
        ],
        preparation: [
          'Em uma panela de fundo grosso, misture o café, o açúcar, o suco de limão e a pectina.',
          'Leve ao fogo médio, mexendo constantemente com uma espátula para dissolver o açúcar.',
          'Quando começar a ferver, continue cozinhando e mexendo por cerca de 10-15 minutos, ou até que a geleia atinja o ponto (quando ela cobre as costas de uma colher e não escorre imediatamente).',
          'Transfira a geleia quente para um pote de vidro esterilizado, feche bem e deixe esfriar.',
        ],
      },
      {
        id: 'creme-de-confeiteiro-de-cafe',
        name: 'Creme de Confeiteiro de Café',
        image: 'creme-de-confeiteiro-de-cafe',
        prepTime: '20 min',
        servings: 'Aprox. 500ml',
        ingredients: [
          '500 ml de leite integral',
          '4 gemas de ovo',
          '100g de açúcar',
          '40g de amido de milho',
          '2 colheres de sopa de café solúvel',
        ],
        preparation: [
          'Aqueça o leite com o café solúvel em uma panela até o café dissolver e o leite estar quente (sem ferver).',
          'Enquanto isso, em uma tigela, bata as gemas com o açúcar e o amido de milho até obter uma mistura clara e homogênea.',
          'Com um fouet, despeje lentamente o leite quente sobre a mistura de gemas, mexendo constantemente para temperar as gemas e evitar que cozinhem.',
          'Retorne a mistura toda para a panela e cozinhe em fogo baixo, mexendo sem parar, até que o creme engrosse e comece a borbulhar.',
          'Transfira o creme para uma tigela, cubra com plástico filme em contato com a superfície para não criar película e leve para gelar. Use para rechear sonhos, bombas e tortas.',
        ],
      },
      {
        id: 'caramelo-de-cafe',
        name: 'Calda de Caramelo de Café',
        image: 'caramelo-de-cafe',
        prepTime: '15 min',
        servings: 'Aprox. 200ml',
        ingredients: [
          '1 xícara (200g) de açúcar',
          '1/4 xícara (60ml) de água',
          '1/2 xícara (120ml) de café forte e quente',
          '1/4 xícara (60ml) de creme de leite',
        ],
        preparation: [
          'Em uma panela, misture o açúcar e a água. Leve ao fogo médio sem mexer, apenas girando a panela ocasionalmente, até formar um caramelo de cor âmbar.',
          'Retire a panela do fogo e, com muito cuidado, despeje o café quente (a mistura irá borbulhar intensamente). Mexa bem.',
          'Adicione o creme de leite e volte ao fogo baixo, mexendo até que a calda fique lisa e homogênea.',
          'Deixe esfriar um pouco antes de usar. A calda engrossará à medida que esfria.',
        ],
      },
      {
        id: 'brigadeiro-de-cafe',
        name: 'Brigadeiro de Café',
        image: 'brigadeiro-de-cafe',
        prepTime: '20 min',
        servings: '20 unidades',
        ingredients: [
          '1 lata de leite condensado',
          '1 colher de sopa de manteiga sem sal',
          '1 colher de sopa de café solúvel',
          '2 colheres de sopa de chocolate em pó',
          'Chocolate granulado ou cacau em pó para enrolar',
        ],
        preparation: [
          'Em uma panela de fundo grosso, coloque o leite condensado, a manteiga, o café solúvel e o chocolate em pó.',
          'Cozinhe em fogo médio-baixo, mexendo constantemente com uma espátula, garantindo que não grude no fundo.',
          'O ponto correto é quando a mistura começa a desgrudar do fundo da panela (ao inclinar a panela, o brigadeiro "cai" em bloco).',
          'Despeje em um prato untado e deixe esfriar completamente. Depois, enrole as bolinhas, passe no granulado e coloque nas forminhas.',
        ],
      },
      {
        id: 'chantilly-de-cafe',
        name: 'Chantilly de Café',
        image: 'chantilly-de-cafe',
        prepTime: '8 min',
        servings: 'Aprox. 300ml',
        ingredients: [
          '250 ml de creme de leite fresco bem gelado (mínimo 35% de gordura)',
          '2 colheres de sopa de açúcar de confeiteiro',
          '1 colher de chá de extrato de café (ou 1 colher de chá de café solúvel diluído em 1 de água fria)',
        ],
        preparation: [
          'Certifique-se de que o creme, a tigela da batedeira e os batedores estejam bem gelados.',
          'Comece batendo o creme de leite em velocidade média. Quando começar a engrossar e formar ondas suaves, adicione o açúcar e o café.',
          'Aumente a velocidade e continue batendo até atingir o ponto de picos firmes (cuidado para não bater demais e virar manteiga).',
          'Use imediatamente para decorar cafés, sobremesas ou frutas.',
        ],
      },
    ],
  },
  {
    id: 'cafes-gourmet-autorais',
    name: 'Cafés Gourmet & Autorais',
    icon: Sparkles,
    recipes: [
      {
        id: 'cafe-com-canela-e-cardamomo',
        name: 'Café com Canela e Cardamomo',
        image: 'cafe-com-canela-e-cardamomo',
        prepTime: '6 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café coado na hora',
          '1 pitada generosa de canela em pó',
          '1 vagem de cardamomo levemente amassada (ou 1 pitada de cardamomo em pó)',
          'Leite ou açúcar a gosto (opcional)',
        ],
        preparation: [
          'Coloque a canela em pó e a vagem de cardamomo amassada diretamente na xícara vazia.',
          'Prepare o seu café coado (V60, Chemex, etc.) despejando a água quente sobre o pó e deixando o café cair diretamente sobre as especiarias na xícara.',
          'A infusão do café quente com as especiarias liberará os óleos essenciais e aromas.',
          'Mexa bem, deixe em infusão por um minuto, e adicione leite ou açúcar se desejar. Coe se preferir não encontrar os pedaços da vagem.',
        ],
      },
      {
        id: 'latte-de-lavanda',
        name: 'Latte de Lavanda',
        image: 'latte-de-lavanda',
        prepTime: '10 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de café espresso',
          '150 ml de leite',
          '1 a 2 colheres de chá de xarope de lavanda caseiro ou comprado',
          'Flores de lavanda secas para decorar (opcional)',
        ],
        preparation: [
          'Comece despejando o xarope de lavanda no fundo da sua xícara ou copo.',
          'Extraia um shot de espresso diretamente sobre o xarope e misture bem.',
          'Vaporize o leite até obter uma textura cremosa e aveludada, perfeita para um latte.',
          'Despeje o leite vaporizado sobre a mistura de espresso e lavanda, criando uma bebida suave e floral.',
          'Decore com algumas flores de lavanda secas na espuma para um charme extra.',
        ],
      },
      {
        id: 'cafe-com-pimenta-e-chocolate',
        name: 'Café com Pimenta e Chocolate',
        image: 'cafe-com-pimenta-e-chocolate',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café forte e quente (prensa francesa ou espresso diluído)',
          '2 quadrados (aprox. 20g) de chocolate meio amargo (70% cacau)',
          '1 pequena pitada de pimenta caiena em pó (comece com pouco!)',
        ],
        preparation: [
          'Coloque os quadrados de chocolate e a pitada de pimenta caiena no fundo de uma xícara resistente ao calor.',
          'Prepare o café bem quente e despeje-o sobre o chocolate e a pimenta.',
          'Deixe descansar por um minuto para que o chocolate comece a derreter.',
          'Com um pequeno batedor ou colher, mexa vigorosamente até que o chocolate esteja completamente derretido e a bebida esteja homogênea.',
          'Experimente e, se ousar, adicione mais uma pitada de pimenta. A combinação do amargor, doçura e picância é surpreendente.',
        ],
      },
      {
        id: 'latte-de-pistache',
        name: 'Latte de Pistache',
        image: 'latte-de-pistache',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '60 ml de espresso duplo',
          '150 ml de leite',
          '1 a 2 colheres de sopa de pasta de pistache pura (ou xarope de pistache)',
          'Pistaches picados para decorar',
        ],
        preparation: [
          'Em sua xícara, coloque a pasta ou xarope de pistache.',
          'Extraia o espresso duplo diretamente sobre a pasta e misture bem até dissolver.',
          'Vaporize o leite até que fique cremoso e com uma microespuma sedosa.',
          'Despeje o leite vaporizado sobre a mistura de café e pistache.',
          'Finalize decorando com pistaches torrados e picados por cima da espuma.',
        ],
      },
      {
        id: 'cafe-com-agua-de-rosas',
        name: 'Café com Água de Rosas',
        image: 'cafe-com-agua-de-rosas',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '1/2 colher de chá de água de rosas de boa qualidade',
          '120 ml de leite vaporizado',
          'Pétalas de rosa secas para uso culinário (opcional, para decorar)',
        ],
        preparation: [
          'Em uma xícara, misture o shot de espresso recém-extraído com a água de rosas.',
          'Vaporize o leite até obter uma espuma cremosa.',
          'Despeje o leite sobre o café aromatizado, como faria em um latte.',
          'Se desejar, decore a superfície com algumas pétalas de rosa secas para um visual elegante e um aroma extra.',
        ],
      },
      {
        id: 'golden-latte-com-cafe',
        name: 'Golden Latte com Café',
        image: 'golden-latte-com-cafe',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '30 ml de espresso',
          '150 ml de leite (leite de amêndoas ou aveia funcionam bem)',
          '1/2 colher de chá de cúrcuma em pó',
          '1 pitada de pimenta preta moída (ajuda na absorção da cúrcuma)',
          '1 colher de chá de mel ou agave',
          '1 pitada de canela (opcional)',
        ],
        preparation: [
          'Em uma panela pequena ou na leiteira da máquina de espresso, aqueça o leite com a cúrcuma, a pimenta preta, a canela e o adoçante, mexendo bem.',
          'Extraia o espresso diretamente na sua xícara.',
          'Despeje a mistura de leite dourado quente sobre o espresso.',
          'Mexa para combinar e sirva esta bebida reconfortante e anti-inflamatória.',
        ],
      },
      {
        id: 'cafe-com-laranja-e-anis',
        name: 'Café com Laranja e Anis',
        image: 'cafe-com-laranja-e-anis',
        prepTime: '7 min',
        servings: '1 xícara',
        ingredients: [
          '18g de café moído para método coado',
          '300ml de água quente',
          '1 casca larga de laranja (sem a parte branca)',
          '1 estrela de anis',
        ],
        preparation: [
          'Coloque a casca de laranja e a estrela de anis no fundo da sua caneca ou jarra.',
          'Posicione seu coador (V60, etc.) sobre o recipiente.',
          'Faça a extração do café como de costume, permitindo que o líquido quente caia sobre as especiarias, extraindo seus aromas.',
          'Após a extração, deixe em infusão por mais um minuto.',
          'Remova a casca e o anis antes de beber para não amargar.',
        ],
      },
      {
        id: 'latte-de-matcha-e-cafe',
        name: 'Latte de Matcha e Café (Dirty Matcha)',
        image: 'latte-de-matcha-e-cafe',
        prepTime: '8 min',
        servings: '1 xícara',
        ingredients: [
          '1 colher de chá de matcha em pó cerimonial',
          '50 ml de água quente (aprox. 80°C)',
          '150 ml de leite frio',
          '30 ml de espresso frio ou em temperatura ambiente',
          'Gelo',
        ],
        preparation: [
          'Em uma tigela pequena, use um batedor de bambu (chasen) para dissolver completamente o matcha na água quente, até formar uma pasta lisa.',
          'Encha um copo de vidro com gelo.',
          'Despeje o leite sobre o gelo.',
          'Com cuidado, despeje a mistura de matcha sobre o leite. Ele se assentará no fundo.',
          'Finalize despejando lentamente o espresso por cima, que formará a camada superior.',
          'Sirva com as camadas visíveis.',
        ],
      },
      {
        id: 'cafe-com-alecrim-e-mel',
        name: 'Café com Alecrim e Mel',
        image: 'cafe-com-alecrim-e-mel',
        prepTime: '10 min',
        servings: '1 xícara',
        ingredients: [
          '1 xícara de café coado forte',
          '1 ramo pequeno de alecrim fresco',
          '1 colher de sopa de mel',
        ],
        preparation: [
          'Em uma panela pequena, aqueça o mel com o ramo de alecrim em fogo muito baixo por 2-3 minutos. Não deixe ferver, apenas o suficiente para que o mel fique fluido e absorva o aroma do alecrim.',
          'Retire o ramo de alecrim e despeje o mel infusionado no fundo da sua xícara.',
          'Prepare o café coado e despeje-o sobre o mel.',
          'Mexa bem para dissolver e sirva, decorando com um novo raminho de alecrim, se desejar.',
        ],
      },
      {
        id: 'iced-latte-de-rosas',
        name: 'Iced Latte de Rosas',
        image: 'iced-latte-de-rosas',
        prepTime: '6 min',
        servings: '1 copo',
        ingredients: [
          '60 ml de espresso',
          '150 ml de leite frio',
          '1 a 2 colheres de sopa de xarope de rosas',
          'Gelo',
          'Pétalas de rosa secas para decorar',
        ],
        preparation: [
          'Encha um copo alto com gelo.',
          'Despeje o xarope de rosas no fundo do copo, seguido pelo leite frio.',
          'Extraia o espresso e despeje-o lentamente sobre o leite para criar camadas.',
          'Decore com algumas pétalas de rosa secas na superfície.',
          'Mexa antes de beber para uma experiência de sabor floral e refrescante.',
        ],
      },
    ],
  },
  {
    id: 'sobremesas-com-cafe',
    name: 'Sobremesas com Café',
    icon: CakeSlice,
    recipes: [
      {
        id: 'tiramisu-classico',
        name: 'Tiramisù Clássico',
        image: 'tiramisu-classico',
        prepTime: '30 min + 4h de geladeira',
        servings: '8 porções',
        ingredients: [
          '4 gemas de ovos frescos',
          '100g de açúcar refinado',
          '500g de queijo mascarpone de boa qualidade',
          '200ml de café espresso forte, frio',
          '30 biscoitos champanhe (savoiardi)',
          'Cacau em pó amargo para polvilhar',
          'Um cálice de licor de café ou Marsala (opcional)',
        ],
        preparation: [
          'Em uma tigela, bata as gemas com o açúcar até a mistura ficar pálida, fofa e o açúcar dissolvido (pode ser em banho-maria para segurança).',
          'Adicione o queijo mascarpone e incorpore delicadamente com uma espátula, sem bater demais, até obter um creme liso.',
          'Misture o café frio com o licor (se usar).',
          'Mergulhe rapidamente cada biscoito na mistura de café (não encharque!) e forme uma camada no fundo de um refratário (aprox. 20x20cm).',
          'Espalhe metade do creme de mascarpone sobre os biscoitos. Repita com outra camada de biscoitos embebidos e o restante do creme.',
          'Cubra e leve à geladeira por pelo menos 4 horas (idealmente de um dia para o outro) para firmar e apurar os sabores.',
          'Pouco antes de servir, polvilhe generosamente com cacau em pó usando uma peneira.',
        ],
      },
      {
        id: 'mousse-de-cafe',
        name: 'Mousse de Café',
        image: 'mousse-de-cafe',
        prepTime: '15 min + 2h de geladeira',
        servings: '6 porções',
        ingredients: [
          '1 lata de leite condensado',
          '1 lata de creme de leite sem soro',
          '1 xícara de café forte e frio',
          '1 envelope (12g) de gelatina em pó sem sabor',
          '5 colheres de sopa de água para hidratar a gelatina',
        ],
        preparation: [
          'Hidrate a gelatina na água e dissolva em banho-maria ou no micro-ondas por 15 segundos, sem deixar ferver.',
          'No liquidificador, coloque o leite condensado, o creme de leite, o café forte e a gelatina dissolvida.',
          'Bata por cerca de 2 minutos, até que a mistura esteja completamente homogênea.',
          'Despeje a mousse em taças individuais ou em um refratário único.',
          'Leve à geladeira por pelo menos 2 horas, ou até que esteja firme. Decore com raspas de chocolate ou grãos de café.',
        ],
      },
      {
        id: 'panna-cotta-de-cafe',
        name: 'Panna Cotta de Café',
        image: 'panna-cotta-de-cafe',
        prepTime: '15 min + 4h de geladeira',
        servings: '6 porções',
        ingredients: [
          '500ml de creme de leite fresco (nata)',
          '100g de açúcar',
          '100ml de café espresso forte',
          '1 envelope (12g) de gelatina em pó sem sabor',
          '5 colheres de sopa de água para hidratar',
        ],
        preparation: [
          'Hidrate a gelatina na água e reserve.',
          'Em uma panela, aqueça o creme de leite com o açúcar em fogo médio, mexendo até o açúcar dissolver. Não deixe ferver.',
          'Adicione o café espresso e misture.',
          'Dissolva a gelatina reservada em banho-maria ou no micro-ondas e adicione à mistura de creme, mexendo bem para incorporar.',
          'Distribua a mistura em forminhas individuais (levemente untadas com óleo neutro para facilitar o desenformar) e leve à geladeira por no mínimo 4 horas.',
          'Desenforme e sirva com calda de chocolate ou caramelo.',
        ],
      },
      {
        id: 'pudim-de-cafe',
        name: 'Pudim de Café',
        image: 'pudim-de-cafe',
        prepTime: '1h30',
        servings: '8 porções',
        ingredients: [
          'Calda: 1 xícara de açúcar, 1/2 xícara de água quente',
          'Pudim: 1 lata de leite condensado, a mesma medida de leite integral, 3 ovos inteiros, 1/2 xícara de café forte',
        ],
        preparation: [
          'Para a calda, derreta o açúcar na forma de pudim em fogo baixo até virar um caramelo dourado. Espalhe pela forma com cuidado e reserve.',
          'No liquidificador, bata o leite condensado, o leite, os ovos e o café até a mistura ficar homogênea.',
          'Despeje a mistura na forma caramelizada.',
          'Cubra a forma com papel alumínio e asse em banho-maria (com água já quente na assadeira) em forno pré-aquecido a 180°C por cerca de 1 hora e 15 minutos, ou até que, ao espetar um palito, ele saia limpo.',
          'Deixe esfriar completamente e leve à geladeira por algumas horas antes de desenformar.',
        ],
      },
      {
        id: 'brownie-de-cafe',
        name: 'Brownie de Café',
        image: 'brownie-de-cafe',
        prepTime: '45 min',
        servings: '9 porções',
        ingredients: [
          '200g de chocolate meio amargo de boa qualidade',
          '100g de manteiga sem sal',
          '1 xícara de açúcar',
          '3 ovos',
          '1 xícara de farinha de trigo',
          '2 colheres de sopa de café solúvel em pó',
          '1 pitada de sal',
          '1 colher de chá de extrato de baunilha',
        ],
        preparation: [
          'Pré-aqueça o forno a 180°C e unte e enfarinhe (ou forre com papel manteiga) uma forma quadrada de 20cm.',
          'Derreta o chocolate com a manteiga em banho-maria ou no micro-ondas. Reserve.',
          'Em outra tigela, bata os ovos com o açúcar até obter um creme claro. Adicione a baunilha.',
          'Incorpore a mistura de chocolate derretido ao creme de ovos. Adicione o café em pó e o sal.',
          'Por último, peneire a farinha de trigo sobre a mistura e incorpore delicadamente, apenas até homogeneizar. Não bata demais.',
          'Despeje na forma e asse por 25-30 minutos. O brownie deve estar firme nas bordas e ligeiramente úmido no centro.',
        ],
      },
      {
        id: 'creme-brulee-de-cafe',
        name: 'Crème Brûlée de Café',
        image: 'creme-brulee-de-cafe',
        prepTime: '1h',
        servings: '4 porções',
        ingredients: [
          '500ml de creme de leite fresco (35% gordura)',
          '100g de açúcar',
          '5 gemas',
          '50ml de café espresso forte',
          'Açúcar demerara para caramelizar',
        ],
        preparation: [
          'Pré-aqueça o forno a 160°C.',
          'Aqueça o creme de leite com o café em uma panela até começar a ferver. Retire do fogo.',
          'Em uma tigela, bata as gemas com o açúcar até obter uma mistura esbranquiçada.',
          'Despeje lentamente o creme quente sobre as gemas, mexendo sem parar para não cozinhar.',
          'Passe a mistura por uma peneira fina e distribua em 4 ramequins (tigelinhas de cerâmica).',
          'Coloque os ramequins em uma assadeira e adicione água quente na assadeira até atingir metade da altura dos ramequins (banho-maria).',
          'Asse por cerca de 40-50 minutos, até o creme estar firme nas bordas mas ainda um pouco tremido no centro.',
          'Retire do forno, deixe esfriar e leve à geladeira por pelo menos 4 horas.',
          'Antes de servir, polvilhe uma camada fina e uniforme de açúcar demerara e queime com um maçarico culinário até caramelizar.',
        ],
      },
      {
        id: 'palha-italiana-de-cafe',
        name: 'Palha Italiana de Café',
        image: 'palha-italiana-de-cafe',
        prepTime: '20 min + 2h de geladeira',
        servings: '12 porções',
        ingredients: [
          '1 lata de leite condensado',
          '1 colher de sopa de café solúvel',
          '3 colheres de sopa de chocolate em pó',
          '1 colher de sopa de manteiga',
          '1 pacote (200g) de biscoito maisena quebrado grosseiramente',
          'Açúcar de confeiteiro para polvilhar',
        ],
        preparation: [
          'Em uma panela, faça um brigadeiro misturando o leite condensado, o café solúvel, o chocolate em pó e a manteiga. Cozinhe em fogo baixo, mexendo sempre, até desgrudar do fundo da panela.',
          'Desligue o fogo e misture o biscoito maisena quebrado.',
          'Despeje a mistura em um refratário pequeno untado com manteiga ou forrado com plástico filme, pressionando para nivelar.',
          'Leve à geladeira por pelo menos 2 horas para firmar.',
          'Corte em quadrados e passe-os no açúcar de confeiteiro.',
        ],
      },
      {
        id: 'semifrio-de-cafe',
        name: 'Semifrio de Café',
        image: 'semifrio-de-cafe',
        prepTime: '30 min + 6h de freezer',
        servings: '8 porções',
        ingredients: [
          '3 gemas',
          '100g de açúcar',
          '250ml de creme de leite fresco batido em ponto de chantilly',
          '100ml de café bem forte e frio',
          'Biscoitos champanhe para a base (opcional)',
        ],
        preparation: [
          'Em uma tigela refratária, bata as gemas com o açúcar sobre uma panela com água fervente (banho-maria), até obter um creme fofo e claro (pâte à bombe).',
          'Retire do fogo e continue batendo na batedeira até a tigela esfriar.',
          'Incorpore o café frio à mistura de gemas.',
          'Delicadamente, com uma espátula, incorpore o chantilly ao creme de café, fazendo movimentos de baixo para cima.',
          'Se usar a base, forre uma forma de bolo inglês com plástico filme e coloque os biscoitos. Despeje o creme por cima.',
          'Leve ao freezer por no mínimo 6 horas. Sirva fatiado.',
        ],
      },
      {
        id: 'cheesecake-de-cafe',
        name: 'Cheesecake de Café',
        image: 'cheesecake-de-cafe',
        prepTime: '1h + 4h de geladeira',
        servings: '10 porções',
        ingredients: [
          'Base: 200g de biscoito de chocolate triturado, 100g de manteiga derretida',
          'Recheio: 500g de cream cheese em temperatura ambiente, 1 lata de leite condensado, 3 ovos, 100ml de café forte',
        ],
        preparation: [
          'Misture o biscoito triturado com a manteiga e forre o fundo de uma forma de fundo removível, pressionando bem. Leve à geladeira.',
          'Na batedeira, bata o cream cheese até ficar liso. Adicione o leite condensado e bata mais.',
          'Adicione os ovos, um de cada vez, batendo apenas para incorporar.',
          'Por fim, misture o café.',
          'Despeje o recheio sobre a base de biscoito e asse em forno pré-aquecido a 160°C por cerca de 45-50 minutos, até as bordas estarem firmes e o centro levemente tremido.',
          'Desligue o forno e deixe o cheesecake esfriar lá dentro. Depois, leve à geladeira por pelo menos 4 horas.',
        ],
      },
      {
        id: 'macarons-de-cafe',
        name: 'Macarons de Café',
        image: 'macarons-de-cafe',
        prepTime: '1h30',
        servings: '20 unidades',
        ingredients: [
          'Casquinhas: 100g de farinha de amêndoas, 100g de açúcar de confeiteiro, 2 claras de ovo envelhecidas, 100g de açúcar refinado, 1 colher de sopa de café solúvel em pó fino',
          'Recheio: Ganache de café',
        ],
        preparation: [
          'Peneire a farinha de amêndoas com o açúcar de confeiteiro e o café em pó.',
          'Faça um merengue francês ou italiano com as claras e o açúcar refinado.',
          'Incorpore os ingredientes secos ao merengue em um processo chamado "macaronage", até a massa cair da espátula em fitas.',
          'Com um saco de confeitar, faça pequenos discos em uma assadeira forrada com papel manteiga. Deixe secar por 30-60 minutos, até formar uma película.',
          'Asse em forno pré-aquecido a 150°C por 15-20 minutos. Os macarons devem formar um "pezinho" (a base enrugada).',
          'Deixe esfriar completamente e recheie os pares de casquinhas com a ganache de café.',
        ],
      },
    ],
  },
  {
    id: 'bolos-tortas-de-cafe',
    name: 'Bolos & Tortas de Café',
    icon: Cake,
    recipes: [
      {
        id: 'bolo-de-cafe-com-nozes',
        name: 'Bolo de Café com Nozes',
        image: 'bolo-de-cafe-com-nozes',
        prepTime: '1 hora',
        servings: '12 fatias',
        ingredients: [
          '3 ovos',
          '1 xícara de açúcar mascavo',
          '1/2 xícara de óleo vegetal',
          '1 xícara de café forte e frio',
          '2 xícaras de farinha de trigo',
          '1 colher de sopa de fermento em pó',
          '1 xícara de nozes picadas grosseiramente',
          '1 pitada de sal',
        ],
        preparation: [
          'Pré-aqueça o forno a 180°C. Unte e enfarinhe uma forma de bolo inglês ou redonda com furo no meio.',
          'Em uma tigela grande, bata os ovos com o açúcar mascavo até obter um creme claro. Adicione o óleo e o café e misture bem.',
          'Peneire a farinha, o fermento e o sal sobre a mistura líquida e incorpore delicadamente com um fouet, sem bater demais.',
          'Adicione as nozes picadas e mexa apenas para distribuir.',
          'Despeje a massa na forma preparada e asse por cerca de 40-45 minutos, ou até que um palito inserido no centro saia limpo.',
          'Deixe o bolo amornar antes de desenformar. Sirva com um glacê de café, se desejar.',
        ],
      },
      {
        id: 'torta-holandesa-de-cafe',
        name: 'Torta Holandesa de Café',
        image: 'torta-holandesa-de-cafe',
        prepTime: '40 min + 3h de geladeira',
        servings: '10 porções',
        ingredients: [
          'Creme: 1 lata de leite condensado, 1/2 xícara de café forte, 200g de creme de leite, 12g de gelatina sem sabor',
          'Base e lateral: 1 pacote de biscoito calipso',
          'Cobertura: 100g de chocolate meio amargo, 100g de creme de leite',
        ],
        preparation: [
          'Hidrate e dissolva a gelatina conforme as instruções.',
          'No liquidificador, bata o leite condensado, o café e o creme de leite. Adicione a gelatina dissolvida e bata mais um pouco.',
          'Em uma forma de fundo removível, disponha os biscoitos calipso em toda a lateral, com a parte do chocolate virada para fora.',
          'Despeje o creme de café na forma com cuidado.',
          'Leve à geladeira por pelo menos 3 horas, ou até firmar.',
          'Para a cobertura, derreta o chocolate com o creme de leite (ganache) e espalhe sobre a torta já firme. Leve à geladeira por mais 30 minutos.',
        ],
      },
      {
        id: 'bolo-formigueiro-com-cafe',
        name: 'Bolo Formigueiro com Café',
        image: 'bolo-formigueiro-com-cafe',
        prepTime: '50 min',
        servings: '12 fatias',
        ingredients: [
          '3 ovos',
          '1 e 1/2 xícara de açúcar',
          '1 xícara de café coado morno',
          '100g de manteiga derretida',
          '2 xícaras de farinha de trigo',
          '1/2 xícara de chocolate granulado',
          '1 colher de sopa de fermento em pó',
        ],
        preparation: [
          'Pré-aqueça o forno a 180°C. Unte uma forma com furo central.',
          'Na batedeira, bata a manteiga com o açúcar até formar um creme. Adicione os ovos, um a um.',
          'Alternadamente, adicione o café e a farinha peneirada, batendo em velocidade baixa.',
          'Desligue a batedeira e incorpore delicadamente o chocolate granulado e o fermento com uma espátula.',
          'Despeje na forma e asse por 35-40 minutos.',
        ],
      },
      {
        id: 'rocambole-de-cafe',
        name: 'Rocambole de Café',
        image: 'rocambole-de-cafe',
        prepTime: '1h',
        servings: '10 fatias',
        ingredients: [
          'Massa: 4 ovos (claras e gemas separadas), 4 colheres de sopa de açúcar, 4 colheres de sopa de farinha, 1 colher de sopa de café solúvel',
          'Recheio: 1 lata de doce de leite misturado com 1 colher de chá de café solúvel',
        ],
        preparation: [
          'Bata as claras em neve firme. Adicione as gemas uma a uma, e depois o açúcar, batendo bem.',
          'Peneire a farinha com o café solúvel e incorpore delicadamente à mistura de ovos.',
          'Asse a massa em uma forma retangular (30x40cm) forrada com papel manteiga, em forno a 180°C, por cerca de 15 minutos.',
          'Desenforme a massa ainda quente sobre um pano de prato limpo e úmido, polvilhado com açúcar.',
          'Espalhe o recheio de doce de leite e enrole o rocambole com a ajuda do pano. Polvilhe açúcar de confeiteiro por cima.',
        ],
      },
      {
        id: 'bolo-de-chocolate-com-calda-de-cafe',
        name: 'Bolo de Chocolate com Calda de Café',
        image: 'bolo-de-chocolate-com-calda-de-cafe',
        prepTime: '1h',
        servings: '12 fatias',
        ingredients: [
          'Bolo: 1 xícara de chocolate em pó 50%, 1 xícara de açúcar, 2 ovos, 1 xícara de leite morno, 1/2 xícara de óleo, 2 xícaras de farinha, 1 colher de sopa de fermento',
          'Calda: 1/2 xícara de café forte, 4 colheres de sopa de açúcar, 2 colheres de sopa de chocolate em pó',
        ],
        preparation: [
          'Bata no liquidificador os ovos, açúcar, óleo e leite. Transfira para uma tigela e misture a farinha e o chocolate.',
          'Adicione o fermento e asse em forma untada a 180°C por 40 minutos.',
          'Para a calda, misture todos os ingredientes em uma panela e ferva por 5 minutos, até engrossar um pouco.',
          'Fure o bolo ainda quente com um garfo e despeje a calda quente por cima, permitindo que ela penetre na massa.',
        ],
      },
      {
        id: 'torta-mousse-de-cafe',
        name: 'Torta Mousse de Café',
        image: 'torta-mousse-de-cafe',
        prepTime: '30 min + 4h de geladeira',
        servings: '10 porções',
        ingredients: [
          'Base: 200g de biscoito de chocolate triturado com 100g de manteiga sem sal derretida',
          'Mousse: 1 lata de leite condensado, 1 de creme de leite, 1 xícara de café forte, 1 envelope de gelatina sem sabor hidratada',
        ],
        preparation: [
          'Misture os ingredientes da base e forre o fundo de uma forma de fundo removível. Leve à geladeira.',
          'No liquidificador, bata todos os ingredientes da mousse até ficar homogêneo.',
          'Despeje a mousse sobre a base de biscoito já firme.',
          'Leve para gelar por no mínimo 4 horas. Decore com raspas de chocolate ou grãos de café.',
        ],
      },
      {
        id: 'bolo-de-fuba-com-cobertura-de-cafe',
        name: 'Bolo de Fubá com Cobertura de Café',
        image: 'bolo-de-fuba-com-cobertura-de-cafe',
        prepTime: '55 min',
        servings: '12 fatias',
        ingredients: [
          'Bolo: 2 xícaras de fubá, 1 xícara de farinha de trigo, 3 ovos, 1 xícara de leite, 1 xícara de óleo, 2 xícaras de açúcar, 1 colher de sopa de fermento',
          'Cobertura: 1 xícara de açúcar de confeiteiro, 3 colheres de sopa de café forte e frio',
        ],
        preparation: [
          'Bata todos os ingredientes do bolo (exceto o fermento) no liquidificador. Por último, misture o fermento.',
          'Asse em forma untada e enfarinhada em forno pré-aquecido a 180°C por cerca de 40 minutos.',
          'Para a cobertura, misture o açúcar de confeiteiro com o café aos poucos, até formar um glacê fluido, mas não muito ralo.',
          'Despeje o glacê sobre o bolo ainda morno.',
        ],
      },
      {
        id: 'torta-de-cafe-com-chantilly',
        name: 'Torta de Café com Chantilly',
        image: 'torta-de-cafe-com-chantilly',
        prepTime: '45 min + geladeira',
        servings: '8 porções',
        ingredients: [
          'Massa: 200g de farinha de trigo, 100g de manteiga gelada, 50g de açúcar, 1 gema',
          'Recheio: 1 receita de creme de confeiteiro de café (ver seção de Cremes)',
          'Cobertura: 250ml de creme de leite fresco batido em chantilly, raspas de chocolate',
        ],
        preparation: [
          'Faça a massa misturando os ingredientes com a ponta dos dedos até formar uma farofa. Pressione no fundo e laterais de uma forma de torta. Fure com um garfo e asse a 180°C até dourar.',
          'Deixe a base da torta esfriar completamente. Em seguida, preencha com o creme de confeiteiro de café já frio.',
          'Leve à geladeira para firmar o recheio.',
          'Antes de servir, cubra com o chantilly e decore com raspas de chocolate.',
        ],
      },
      {
        id: 'cuca-de-cafe',
        name: 'Cuca de Café',
        image: 'cuca-de-cafe',
        prepTime: '1h',
        servings: '12 porções',
        ingredients: [
          'Massa: 3 xícaras de farinha, 2 xícaras de açúcar, 3 ovos, 1 xícara de leite com 1 colher de sopa de café solúvel, 1 colher de sopa de fermento',
          'Farofa: 1 xícara de farinha, 1 xícara de açúcar, 100g de manteiga gelada, canela em pó a gosto',
        ],
        preparation: [
          'Para a farofa, misture os ingredientes com a ponta dos dedos até formar uma farofa úmida e reserve.',
          'Para a massa, bata os ovos com o açúcar. Adicione o leite com café e, aos poucos, a farinha. Por último, o fermento.',
          'Despeje a massa em uma forma retangular untada e espalhe a farofa por cima de maneira uniforme.',
          'Asse em forno pré-aquecido a 180°C por 40-50 minutos, ou até a farofa dourar e o bolo estar assado.',
        ],
      },
      {
        id: 'bolo-invertido-de-cafe-e-banana',
        name: 'Bolo Invertido de Café e Banana',
        image: 'bolo-invertido-de-cafe-e-banana',
        prepTime: '1h10',
        servings: '10 fatias',
        ingredients: [
          'Calda: 1 xícara de açúcar, 1/2 xícara de café forte',
          '4 bananas nanicas fatiadas no comprimento',
          'Massa: massa de bolo simples de sua preferência (ex: iogurte), adicionando 1/2 xícara de café à massa',
        ],
        preparation: [
          'Faça a calda derretendo o açúcar em uma forma redonda e adicionando o café com cuidado. Espalhe pelo fundo.',
          'Disponha as fatias de banana sobre a calda, cobrindo todo o fundo da forma.',
          'Prepare a massa do bolo de sua preferência, incorporando o café.',
          'Despeje a massa cuidadosamente sobre as bananas.',
          'Asse a 180°C por cerca de 45 minutos. É importante desenformar o bolo ainda morno para que a calda não endureça na forma.',
        ],
      },
    ],
  },
  {
    id: 'massas-receitas-salgadas-com-cafe',
    name: 'Massas & Receitas Salgadas',
    icon: UtensilsCrossed,
    recipes: [
      {
        id: 'risoto-de-cafe',
        name: 'Risoto de Café',
        image: 'risoto-de-cafe',
        prepTime: '30 min',
        servings: '2 porções',
        ingredients: [
          '1 xícara de arroz arbóreo',
          '1/2 cebola bem picada',
          '50 ml de café espresso',
          '1 litro de caldo de legumes quente',
          '50g de queijo parmesão ralado na hora',
          '1 colher de sopa de manteiga gelada',
          'Azeite, sal e pimenta do reino',
        ],
        preparation: [
          'Em uma panela, aqueça um fio de azeite e refogue a cebola até ficar translúcida.',
          'Adicione o arroz e frite por cerca de 1 minuto ("tostar").',
          'Despeje o café espresso e mexa até evaporar completamente.',
          'Comece a adicionar o caldo de legumes quente, uma concha por vez, mexendo sempre e esperando o líquido ser absorvido antes de adicionar mais.',
          'Continue esse processo por cerca de 15-18 minutos, até o arroz estar al dente (cozido mas ainda com uma leve resistência no centro).',
          'Desligue o fogo, adicione a manteiga gelada e o queijo parmesão. Mexa vigorosamente para criar cremosidade (mantecatura). Tempere com sal e pimenta e sirva imediatamente.',
        ],
      },
      {
        id: 'molho-barbecue-de-cafe',
        name: 'Molho Barbecue de Café',
        image: 'molho-barbecue-de-cafe',
        prepTime: '25 min',
        servings: 'Aprox. 300 ml',
        ingredients: [
          '1 xícara de ketchup',
          '1/4 xícara de café forte e coado',
          '2 colheres de sopa de vinagre de maçã',
          '3 colheres de sopa de açúcar mascavo',
          '1 colher de sopa de molho inglês',
          '1 colher de chá de páprica defumada',
          '1/2 colher de chá de cominho em pó',
        ],
        preparation: [
          'Em uma panela, combine todos os ingredientes: ketchup, café, vinagre, açúcar mascavo, molho inglês e as especiarias.',
          'Misture bem e leve ao fogo baixo.',
          'Cozinhe por cerca de 20 a 25 minutos, mexendo ocasionalmente, até que o molho reduza e engrosse, apurando os sabores.',
          'Deixe esfriar antes de usar. Perfeito para pincelar em carnes na churrasqueira ou como acompanhamento para hambúrgueres e batatas fritas.',
        ],
      },
      {
        id: 'costela-ao-molho-de-cafe',
        name: 'Costela Suína ao Molho de Café',
        image: 'costela-ao-molho-de-cafe',
        prepTime: '3h',
        servings: '4 porções',
        ingredients: [
          '1 kg de costela suína em ripas',
          'Marinada: 200ml de café forte, 4 dentes de alho amassados, sal, pimenta do reino, 1 folha de louro',
          'Molho: caldo do cozimento, 1 colher de sopa de amido de milho',
        ],
        preparation: [
          'Tempere a costela com todos os ingredientes da marinada e deixe descansar na geladeira por pelo menos 2 horas (idealmente de um dia para o outro).',
          'Transfira a costela e a marinada para uma panela de pressão, adicione um pouco de água se necessário para cobrir 1/3 da carne. Cozinhe por 40 minutos após pegar pressão.',
          '(Alternativa ao forno): Coloque em uma assadeira, cubra com papel alumínio e asse a 180°C por 2 horas ou até a carne ficar bem macia.',
          'Retire a costela da panela/assadeira e reserve. Coe o caldo que se formou e leve a uma panela.',
          'Dissolva o amido de milho em um pouco de água fria e adicione ao caldo, cozinhando em fogo baixo até engrossar.',
          'Sirva a costela regada com o molho de café.',
        ],
      },
      {
        id: 'rub-de-cafe-para-carnes',
        name: 'Dry Rub de Café para Carnes',
        image: 'rub-de-cafe-para-carnes',
        prepTime: '5 min',
        servings: 'Aprox. 1/2 xícara',
        ingredients: [
          '3 colheres de sopa de café moído (não solúvel)',
          '2 colheres de sopa de páprica defumada',
          '2 colheres de sopa de açúcar mascavo',
          '1 colher de sopa de sal',
          '1 colher de chá de pimenta preta moída na hora',
          '1 colher de chá de cominho em pó',
          '1 colher de chá de alho em pó',
        ],
        preparation: [
          'Em uma tigela, misture bem todos os ingredientes secos: o café, a páprica, o açúcar, o sal, a pimenta, o cominho e o alho em pó.',
          'Certifique-se de que não há grumos de açúcar mascavo.',
          'Armazene em um pote hermeticamente fechado.',
          'Para usar, seque bem a peça de carne (bife de chorizo, costela, etc.) e esfregue o tempero generosamente por toda a superfície antes de grelhar, assar ou defumar.',
        ],
      },
      {
        id: 'vinagrete-de-cafe',
        name: 'Vinagrete de Café',
        image: 'vinagrete-de-cafe',
        prepTime: '5 min',
        servings: 'Aprox. 150ml',
        ingredients: [
          '100 ml de azeite de oliva extra virgem',
          '30 ml de café espresso frio',
          '20 ml de vinagre balsâmico',
          '1 colher de chá de mostarda Dijon',
          '1 colher de chá de mel ou maple syrup',
          'Sal e pimenta do reino a gosto',
        ],
        preparation: [
          'Coloque todos os ingredientes (azeite, café, balsâmico, Dijon, mel, sal e pimenta) em um pote de vidro com tampa.',
          'Feche bem a tampa e agite vigorosamente por cerca de 30 segundos, ou até que o molho emulsione e fique ligeiramente cremoso.',
          'Prove e ajuste o sal ou a doçura se necessário.',
          'Este molho é excelente para saladas com folhas amargas (como radicchio), rúcula, nozes e queijos fortes como gorgonzola.',
        ],
      },
      {
        id: 'chilli-com-carne-e-cafe',
        name: 'Chilli com Carne e Café',
        image: 'chilli-com-carne-e-cafe',
        prepTime: '1h',
        servings: '6 porções',
        ingredients: [
          '500g de carne moída (patinho ou acém)',
          '1 lata de feijão vermelho cozido e escorrido',
          '1 lata de tomate pelado em cubos',
          '1 cebola grande picada',
          '2 dentes de alho picados',
          '100ml de café forte coado',
          'Pimenta em pó (chilli ou outra) e cominho a gosto',
        ],
        preparation: [
          'Em uma panela grande, doure a carne moída. Retire e reserve.',
          'Na mesma panela, refogue a cebola e o alho até ficarem macios.',
          'Retorne a carne para a panela. Adicione o tomate pelado, o café, a pimenta e o cominho. Tempere com sal.',
          'Deixe cozinhar em fogo baixo, com a panela semi-tampada, por pelo menos 45 minutos para apurar os sabores.',
          'Adicione o feijão cozido, misture e cozinhe por mais 10 minutos.',
          'Sirva quente com sour cream, coentro e tortilhas.',
        ],
      },
      {
        id: 'sopa-de-cebola-com-toque-de-cafe',
        name: 'Sopa de Cebola com Toque de Café',
        image: 'sopa-de-cebola-com-toque-de-cafe',
        prepTime: '50 min',
        servings: '4 porções',
        ingredients: [
          '4 cebolas grandes fatiadas finamente',
          '1 litro de caldo de carne de boa qualidade',
          '50ml de café coado forte',
          '4 fatias de pão tipo baguete',
          '150g de queijo Gruyère ou Emmental ralado',
          'Manteiga, azeite, sal e pimenta',
        ],
        preparation: [
          'Em uma panela grande, derreta 2 colheres de sopa de manteiga com um fio de azeite. Adicione as cebolas e cozinhe em fogo baixo por 20-30 minutos, mexendo sempre, até que estejam bem macias e caramelizadas.',
          'Adicione o caldo de carne e o café. Tempere com sal e pimenta e deixe ferver em fogo baixo por mais 15 minutos.',
          'Toste as fatias de pão no forno.',
          'Distribua a sopa em cumbucas refratárias, coloque uma fatia de pão sobre cada uma e cubra generosamente com o queijo ralado.',
          'Leve ao forno para gratinar até o queijo derreter e dourar.',
        ],
      },
      {
        id: 'file-mignon-ao-molho-de-cafe',
        name: 'Filé Mignon ao Molho de Café',
        image: 'file-mignon-ao-molho-de-cafe',
        prepTime: '25 min',
        servings: '2 porções',
        ingredients: [
          '2 medalhões altos de filé mignon (aprox. 200g cada)',
          'Molho: 50ml de café espresso, 100ml de creme de leite fresco, 1 dose de conhaque ou whisky, 1 colher de chá de manteiga',
          'Sal e pimenta do reino moída na hora',
        ],
        preparation: [
          'Tempere os medalhões com sal e pimenta.',
          'Em uma frigideira quente com um fio de azeite, sele a carne de todos os lados até dourar. Cozinhe até o ponto desejado e reserve os medalhões em local aquecido.',
          'Na mesma frigideira, com cuidado, deglaceie com o conhaque (incline a frigideira para flambar, se tiver experiência).',
          'Adicione o café e deixe reduzir um pouco. Abaixe o fogo, adicione o creme de leite e a manteiga, mexendo até o molho ficar cremoso e homogêneo.',
          'Sirva os medalhões regados com o molho de café.',
        ],
      },
      {
        id: 'cogumelos-salteados-com-cafe',
        name: 'Cogumelos Salteados com Café',
        image: 'cogumelos-salteados-com-cafe',
        prepTime: '15 min',
        servings: '2 porções',
        ingredients: [
          '300g de cogumelos frescos variados (Paris, Portobello, Shiitake), fatiados',
          '2 dentes de alho fatiados',
          '30ml de café espresso',
          'Salsinha fresca picada, sal, pimenta',
          'Azeite e 1 colher de chá de manteiga',
        ],
        preparation: [
          'Aqueça bem uma frigideira grande. Adicione um fio de azeite e a manteiga.',
          'Adicione os cogumelos e salteie em fogo alto, sem mexer muito no início, para que dourem.',
          'Quando os cogumelos estiverem dourados, adicione o alho e refogue por mais um minuto.',
          'Despeje o café e mexa, raspando o fundo da frigideira. Deixe o líquido evaporar quase completamente.',
          'Tempere com sal e pimenta a gosto e finalize com a salsinha picada.',
          'Sirva como acompanhamento para carnes ou sobre uma torrada.',
        ],
      },
      {
        id: 'hamburguer-com-maionese-de-cafe',
        name: 'Hambúrguer com Maionese de Café',
        image: 'hamburguer-com-maionese-de-cafe',
        prepTime: '20 min',
        servings: '4 porções',
        ingredients: [
          '4 hambúrgueres de 150g cada',
          '4 pães de hambúrguer',
          'Queijo prato ou cheddar, bacon frito, alface, tomate',
          'Maionese: 1 xícara de maionese de boa qualidade, 1 colher de sopa de café solúvel diluído em 1 colher de chá de água',
        ],
        preparation: [
          'Prepare a maionese: em uma tigela, misture a maionese com o café diluído até ficar um creme homogêneo e de cor uniforme. Reserve na geladeira.',
          'Grelhe os hambúrgueres na chapa ou frigideira até o ponto desejado. Nos últimos minutos, coloque o queijo por cima para derreter.',
          'Toste levemente os pães.',
          'Monte o lanche: passe uma camada generosa da maionese de café na base do pão, coloque o hambúrguer com queijo, bacon, alface, tomate e feche o pão.',
        ],
      },
    ],
  },
  {
    id: 'fitness-saudaveis-com-cafe',
    name: 'Fitness & Saudáveis com Café',
    icon: HeartPulse,
    recipes: [
      {
        id: 'smoothie-de-cafe-e-banana',
        name: 'Smoothie de Café e Banana',
        image: 'smoothie-de-cafe-e-banana',
        prepTime: '5 min',
        servings: '1 copo',
        ingredients: [
          '1 banana prata madura congelada em rodelas',
          '100 ml de café forte, já frio',
          '1/2 pote de iogurte natural desnatado (ou 100ml de leite vegetal)',
          '1 colher de sopa de sementes de chia ou linhaça',
          'Canela em pó a gosto',
        ],
        preparation: [
          'Certifique-se de que a banana e o café estão bem gelados para uma melhor textura.',
          'Coloque todos os ingredientes no liquidificador: a banana congelada, o café frio, o iogurte e as sementes.',
          'Bata em alta velocidade até que a mistura se torne um creme liso, espesso e homogêneo.',
          'Se necessário, pare para raspar as laterais do liquidificador e bata novamente.',
          'Despeje em um copo e sirva imediatamente. Pode polvilhar mais canela por cima.',
        ],
      },
      {
        id: 'proteina-gelada-com-cafe',
        name: 'Proteína Gelada com Café',
        image: 'proteina-gelada-com-cafe',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: [
          '1 scoop (aprox. 30g) de whey protein (sabor baunilha, chocolate ou café)',
          '150 ml de café forte, já frio',
          '5 a 6 cubos de gelo',
          'Adoçante a gosto, se necessário',
        ],
        preparation: [
          'Em uma coqueteleira (shaker) ou no liquidificador, adicione o café frio.',
          'Acrescente o scoop de whey protein e o adoçante, se estiver usando.',
          'Agite ou bata bem até dissolver todo o pó.',
          'Adicione os cubos de gelo e agite/bata novamente até a bebida ficar bem gelada e ligeiramente espumosa.',
          'Ótima opção para um pré-treino ou um lanche rápido e proteico.',
        ],
      },
      {
        id: 'mingau-de-aveia-com-cafe',
        name: 'Mingau de Aveia com Café (Overnight Oats)',
        image: 'mingau-de-aveia-com-cafe',
        prepTime: '5 min + 8h de geladeira',
        servings: '1 porção',
        ingredients: [
          '1/2 xícara de aveia em flocos',
          '1/2 xícara de leite desnatado ou vegetal',
          '1/4 xícara de café coado forte e frio',
          '1 colher de sopa de chia',
          'Adoçante natural (stévia, xilitol) a gosto',
          'Frutas e nozes para servir',
        ],
        preparation: [
          'Em um pote de vidro com tampa, combine a aveia, o leite, o café frio, a chia e o adoçante.',
          'Misture tudo muito bem, garantindo que a chia não fique aglomerada no fundo.',
          'Tampe o pote e leve à geladeira por pelo menos 4 horas, mas o ideal é deixar durante a noite (overnight).',
          'Na manhã seguinte, o mingau estará espesso e pronto para comer.',
          'Sirva frio, direto do pote, e adicione toppings como banana fatiada, morangos ou um punhado de amêndoas.',
        ],
      },
      {
        id: 'barrinha-de-proteina-e-cafe',
        name: 'Barrinha de Proteína e Café',
        image: 'barrinha-de-proteina-e-cafe',
        prepTime: '15 min + 1h de geladeira',
        servings: '8 barrinhas',
        ingredients: [
          '1 xícara de tâmaras sem caroço',
          '1 xícara de castanhas ou amêndoas',
          '1/2 xícara de aveia em flocos',
          '2 scoops de whey protein de chocolate ou baunilha',
          '2 colheres de sopa de café forte (líquido)',
          '1 colher de sopa de cacau em pó (opcional)',
        ],
        preparation: [
          'Se as tâmaras estiverem secas, hidrate-as em água morna por 10 minutos e escorra.',
          'Em um processador de alimentos, processe as tâmaras e as castanhas até formar uma pasta grossa e pegajosa.',
          'Adicione a aveia, o whey protein, o café e o cacau (se usar). Processe novamente até que todos os ingredientes formem uma massa homogênea.',
          'Forre uma forma pequena com plástico filme ou papel manteiga. Pressione a massa firmemente na forma, deixando-a com cerca de 2cm de espessura.',
          'Leve à geladeira por pelo menos 1 hora para firmar.',
          'Retire da forma e corte em 8 barrinhas. Mantenha refrigerado.',
        ],
      },
      {
        id: 'cafe-a-prova-de-balas-bulletproof',
        name: 'Café à Prova de Balas (Bulletproof)',
        image: 'cafe-a-prova-de-balas-bulletproof',
        prepTime: '5 min',
        servings: '1 xícara',
        ingredients: [
          '250 ml de café de alta qualidade, coado e quente',
          '1 colher de sopa de manteiga ghee (ou manteiga sem sal de gado de pasto)',
          '1 colher de sopa de óleo de coco extravirgem (ou óleo MCT)',
        ],
        preparation: [
          'Prepare o café usando seu método preferido (prensa francesa e aeropress são ótimas opções).',
          'Em um liquidificador (de preferência de vidro, para aguentar o calor), coloque o café quente recém-preparado.',
          'Adicione a ghee e o óleo de coco.',
          'Tampe bem o liquidificador e bata em alta velocidade por 20 a 30 segundos. A bebida vai emulsionar, criando uma camada cremosa e espumosa no topo, parecida com a de um latte.',
          'Sirva imediatamente em uma xícara e consuma enquanto estiver quente. Fornece energia e saciedade.',
        ],
      },
      {
        id: 'pudim-de-chia-com-cafe',
        name: 'Pudim de Chia com Café',
        image: 'pudim-de-chia-com-cafe',
        prepTime: '5 min + 4h de geladeira',
        servings: '2 porções',
        ingredients: [
          '1/4 xícara (4 colheres de sopa) de sementes de chia',
          '1 xícara de leite de amêndoas ou coco',
          '1/4 xícara de café forte e frio',
          '1 colher de sopa de xarope de ácer (maple syrup) ou agave',
          '1/2 colher de chá de extrato de baunilha',
        ],
        preparation: [
          'Em uma tigela ou pote de vidro, misture as sementes de chia, o leite, o café frio, o xarope e a baunilha.',
          'Com um garfo ou pequeno batedor, mexa bem por cerca de 1 minuto para evitar que as sementes grudem.',
          'Deixe descansar por 5 minutos e mexa novamente.',
          'Cubra e leve à geladeira por pelo menos 4 horas (ou de um dia para o outro) até que o pudim adquira uma consistência gelatinosa e espessa.',
          'Sirva gelado, com frutas vermelhas ou nibs de cacau por cima.',
        ],
      },
      {
        id: 'nice-cream-de-cafe',
        name: '"Nice Cream" de Café',
        image: 'nice-cream-de-cafe',
        prepTime: '5 min',
        servings: '2 porções',
        ingredients: [
          '2 bananas maduras congeladas em rodelas',
          '1 colher de sopa de café solúvel em pó',
          '1 colher de sopa de leite vegetal (apenas se necessário para bater)',
          'Nibs de cacau para decorar (opcional)',
        ],
        preparation: [
          'Coloque as rodelas de banana congelada em um processador de alimentos ou liquidificador potente.',
          'Adicione o café solúvel em pó.',
          'Bata em alta velocidade. A mistura passará por estágios (farelo, pedaços, até virar um creme liso). Pode ser necessário parar e raspar as laterais do aparelho.',
          'Se o seu aparelho estiver com dificuldade, adicione a colher de leite para ajudar a bater.',
          'Assim que atingir a consistência de um sorvete cremoso, sirva imediatamente. Decore com nibs de cacau.',
        ],
      },
      {
        id: 'muffins-fit-de-cafe-e-cacau',
        name: 'Muffins Fit de Café e Cacau',
        image: 'muffins-fit-de-cafe-e-cacau',
        prepTime: '30 min',
        servings: '12 muffins',
        ingredients: [
          '1 xícara de farinha de aveia',
          '2 ovos',
          '1/2 xícara de iogurte grego natural',
          '1/2 xícara de café forte e frio',
          '1/4 xícara de cacau em pó 100%',
          '3 colheres de sopa de adoçante culinário (xilitol, eritritol)',
          '1 colher de chá de fermento em pó',
        ],
        preparation: [
          'Pré-aqueça o forno a 180°C e prepare forminhas de muffin.',
          'Em uma tigela, misture os ingredientes líquidos: ovos, iogurte e café.',
          'Em outra tigela, combine os ingredientes secos: farinha de aveia, cacau, adoçante e fermento.',
          'Despeje os líquidos sobre os secos e misture apenas o suficiente para incorporar. Não misture em excesso.',
          'Distribua a massa nas forminhas, preenchendo cerca de 2/3 de cada uma.',
          'Asse por 15 a 20 minutos, ou até que um palito inserido no centro saia limpo.',
        ],
      },
      {
        id: 'bolinhas-energeticas-de-cafe',
        name: 'Bolinhas Energéticas de Café',
        image: 'bolinhas-energeticas-de-cafe',
        prepTime: '10 min',
        servings: '15 bolinhas',
        ingredients: [
          '1 xícara de aveia em flocos',
          '1/2 xícara de pasta de amendoim',
          '1/3 xícara de mel ou agave',
          '1 colher de sopa de café moído fino (não solúvel)',
          '1/2 xícara de gotas de chocolate amargo ou nibs de cacau',
          '1 colher de sopa de sementes de chia',
        ],
        preparation: [
          'Em uma tigela, combine todos os ingredientes: aveia, pasta de amendoim, mel, café moído, gotas de chocolate e chia.',
          'Misture bem com uma colher até formar uma massa homogênea e um pouco pegajosa.',
          'Se a massa estiver muito seca, adicione um pouco mais de pasta de amendoim; se estiver muito mole, adicione mais aveia.',
          'Com as mãos, enrole pequenas porções da massa para formar bolinhas do tamanho de uma noz.',
          'Coloque as bolinhas em um prato e leve à geladeira por pelo menos 30 minutos para firmar. Mantenha refrigerado.',
        ],
      },
      {
        id: 'crepioca-de-cafe',
        name: 'Crepioca de Café',
        image: 'crepioca-de-cafe',
        prepTime: '7 min',
        servings: '1 porção',
        ingredients: [
          '1 ovo',
          '2 colheres de sopa de goma de tapioca hidratada',
          '1 colher de chá de café solúvel',
          'Recheio a gosto (ex: pasta de amendoim, banana amassada com canela, queijo cottage)',
        ],
        preparation: [
          'Em uma tigela pequena, bata o ovo com um garfo. Adicione a goma de tapioca e o café solúvel.',
          'Misture bem até que a massa fique líquida e homogênea, sem grumos de tapioca ou café.',
          'Aqueça uma frigideira antiaderente em fogo médio-baixo.',
          'Despeje a massa na frigideira e espalhe para formar um disco, como uma panqueca.',
          'Cozinhe por cerca de 2-3 minutos de um lado, até firmar. Vire e cozinhe por mais 1 minuto.',
          'Retire da frigideira, adicione o recheio de sua preferência em uma metade e dobre.',
        ],
      },
    ],
  },
  {
    id: 'drinks-coqueteis-com-cafe',
    name: 'Drinks & Coquetéis com Café',
    icon: Martini,
    recipes: [
      {
        id: 'espresso-martini',
        name: 'Espresso Martini',
        image: 'espresso-martini',
        prepTime: '5 min',
        servings: '1 taça',
        ingredients: [
          '50 ml de vodka',
          '30 ml de licor de café (como Kahlúa ou Tía Maria)',
          '30 ml de café espresso recém-extraído e quente',
          '10 ml de xarope de açúcar (opcional, se preferir mais doce)',
          'Gelo',
          '3 grãos de café para decorar',
        ],
        preparation: [
          'Primeiro, gele sua taça de martini ou coupé, enchendo-a com gelo e água enquanto prepara o drink.',
          'Encha uma coqueteleira com cubos de gelo.',
          'Adicione a vodka, o licor de café, o espresso quente (isso ajuda a criar a espuma característica) e o xarope de açúcar, se usar.',
          'Feche bem a coqueteleira e agite vigorosamente por cerca de 15 segundos. A coqueteleira deve ficar bem gelada por fora.',
          'Descarte o gelo da taça. Faça uma coagem dupla (usando o coador da coqueteleira e uma peneira fina) para a taça gelada, garantindo uma espuma cremosa e sem cristais de gelo.',
          'Decore com os três grãos de café flutuando sobre a espuma, que representam saúde, riqueza e felicidade.',
        ],
      },
      {
        id: 'irish-coffee',
        name: 'Irish Coffee',
        image: 'irish-coffee',
        prepTime: '7 min',
        servings: '1 taça',
        ingredients: [
          '40 ml de uísque irlandês',
          '1 a 2 colheres de chá de açúcar mascavo',
          '120 ml de café quente, forte e coado',
          'Creme de leite fresco (nata) levemente batido',
        ],
        preparation: [
          'Aqueça uma taça de vidro com água quente por um minuto e depois descarte a água. Isso evita que a bebida esfrie rápido.',
          'Adicione o açúcar mascavo no fundo da taça, seguido pelo uísque irlandês. Mexa até dissolver o açúcar.',
          'Despeje o café quente sobre a mistura, deixando um espaço de cerca de 2 cm até a borda.',
          'Para a cobertura, bata levemente o creme de leite fresco até que ele engrosse um pouco, mas ainda esteja líquido (ponto de fita).',
          'Com muito cuidado, despeje o creme sobre as costas de uma colher aquecida, encostada na borda interna da taça. O creme deve flutuar sobre o café, criando duas camadas distintas. Não misture; beba o café quente através do creme frio.',
        ],
      },
      {
        id: 'black-russian',
        name: 'Black Russian',
        image: 'black-russian',
        prepTime: '3 min',
        servings: '1 copo',
        ingredients: ['50 ml de vodka', '20 ml de licor de café', 'Gelo'],
        preparation: [
          'Encha um copo baixo (old fashioned) com cubos de gelo.',
          'Despeje a vodka sobre o gelo.',
          'Em seguida, adicione o licor de café.',
          'Mexa suavemente com uma colher bailarina apenas para misturar os ingredientes e gelar.',
          'Sirva imediatamente. É um drink simples, forte e elegante.',
        ],
      },
      {
        id: 'white-russian',
        name: 'White Russian',
        image: 'white-russian',
        prepTime: '4 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de vodka',
          '20 ml de licor de café',
          '30 ml de creme de leite fresco (ou half-and-half)',
          'Gelo',
        ],
        preparation: [
          'Encha um copo baixo com gelo.',
          'Adicione a vodka e o licor de café e mexa.',
          'Para criar o efeito clássico, despeje o creme de leite fresco cuidadosamente sobre as costas de uma colher, para que ele flutue sobre a mistura escura.',
          'Sirva assim para o apelo visual, e quem for beber pode mexer antes de consumir para criar uma bebida cremosa e homogênea.',
        ],
      },
      {
        id: 'revolver-cocktail',
        name: 'Revolver Cocktail',
        image: 'revolver-cocktail',
        prepTime: '4 min',
        servings: '1 taça',
        ingredients: [
          '60 ml de bourbon',
          '15 ml de licor de café',
          '2 dashes (lances) de orange bitters',
          'Uma casca de laranja para decorar',
        ],
        preparation: [
          'Gele uma taça coupé ou de martini.',
          'Em um mixing glass (copo misturador) com gelo, adicione o bourbon, o licor de café e os dashes de orange bitters.',
          'Mexa bem com uma colher bailarina por cerca de 20 segundos para gelar e diluir adequadamente.',
          'Coe a bebida para a taça previamente gelada.',
          'Para decorar, torça a casca de laranja sobre o drink para liberar os óleos essenciais na superfície e, em seguida, coloque-a dentro do copo.',
        ],
      },
      {
        id: 'carajillo',
        name: 'Carajillo',
        image: 'carajillo',
        prepTime: '5 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de Licor 43',
          '50 ml de café espresso quente',
          'Gelo',
        ],
        preparation: [
          'Existem duas formas populares de preparo: a simples e a batida em coqueteleira.',
          'Método simples: Encha um copo baixo com gelo. Despeje o Licor 43 e, em seguida, o espresso quente por cima. Mexa e sirva.',
          'Método batido (mais cremoso): Em uma coqueteleira com gelo, adicione o Licor 43 e o espresso quente. Agite vigorosamente até gelar bem.',
          'Coe para um copo baixo com gelo fresco. A agitação cria uma espuma agradável.',
        ],
      },
      {
        id: 'negroni-com-cafe',
        name: 'Negroni com Infusão de Café',
        image: 'negroni-com-cafe',
        prepTime: '5 min (+ infusão)',
        servings: '1 copo',
        ingredients: [
          '30 ml de gin',
          '30 ml de Campari com infusão de café*',
          '30 ml de vermute tinto',
          'Gelo e uma fatia de laranja',
        ],
        preparation: [
          '*Para a infusão: em um pote, misture 250ml de Campari com 25g de grãos de café levemente quebrados. Deixe infusionar por 4 a 6 horas em temperatura ambiente e depois coe bem.',
          'Em um copo baixo (old fashioned), adicione uma pedra grande de gelo.',
          'Despeje o gin, o Campari infusionado e o vermute tinto.',
          'Mexa suavemente com uma colher bailarina por cerca de 15 segundos.',
          'Decore com uma fatia de laranja.',
        ],
      },
      {
        id: 'cold-brew-gin-tonica',
        name: 'Cold Brew Gin & Tônica',
        image: 'cold-brew-gin-tonica',
        prepTime: '4 min',
        servings: '1 copo',
        ingredients: [
          '50 ml de gin',
          '30 ml de concentrado de cold brew',
          '120 ml de água tônica de boa qualidade',
          'Gelo e uma rodela de limão ou toranja',
        ],
        preparation: [
          'Encha uma taça de gin (copa balão) ou um copo alto com bastante gelo para manter a bebida bem gelada e com menos diluição.',
          'Adicione o gin e o cold brew.',
          'Incline o copo e despeje lentamente a água tônica para preservar a carbonatação.',
          'Mexa uma única vez, de baixo para cima, muito suavemente.',
          'Decore com uma rodela de limão ou toranja.',
        ],
      },
      {
        id: 'old-fashioned-de-cafe',
        name: 'Old Fashioned de Café',
        image: 'old-fashioned-de-cafe',
        prepTime: '6 min',
        servings: '1 copo',
        ingredients: [
          '60 ml de rye whiskey ou bourbon',
          '1 colher de chá de xarope de café*',
          '2 dashes de Angostura bitters',
          'Casca de laranja para decorar',
        ],
        preparation: [
          '*Para o xarope de café: dissolva 1 parte de açúcar em 1 parte de café forte quente e deixe esfriar.',
          'Em um copo baixo (mixing glass), adicione o xarope de café e os bitters.',
          'Adicione o whiskey e gelo. Mexa por cerca de 20 segundos.',
          'Coe para um outro copo baixo com uma pedra grande de gelo fresco.',
          'Torça uma casca de laranja sobre o copo para liberar seus óleos e use-a para decorar.',
        ],
      },
      {
        id: 'batida-de-cafe',
        name: 'Batida de Café',
        image: 'batida-de-cafe',
        prepTime: '5 min',
        servings: '2 copos',
        ingredients: [
          '100 ml de cachaça de boa qualidade',
          '100 ml de café coado forte e frio',
          '1/2 lata de leite condensado',
          'Gelo a gosto',
        ],
        preparation: [
          'No liquidificador, coloque o gelo, a cachaça, o café frio e o leite condensado.',
          'Bata em alta velocidade até que a mistura esteja cremosa, homogênea e o gelo bem triturado.',
          'Prove e ajuste a doçura ou a quantidade de cachaça se necessário.',
          'Sirva imediatamente em copos, podendo decorar com canela em pó por cima.',
        ],
      },
    ],
  },
];

export const getRecipeById = (id: string) => {
  for (const category of categories) {
    const recipe = category.recipes.find(recipe => recipe.id === id);
    if (recipe) {
      return recipe;
    }
  }
  return null;
};
